### ISSUE TITLE
Upper bounds on supported Julia versions

### ISSUE THREAD

**Issue by iamed2** [JuliaGraphs/LightGraphs.jl#570] opened 2017-03-28 17:37 UTC
Right now LightGraphs supports `julia 0.5`, which means any Julia release greater than or equal to the first 0.5 release. Therefore, 0.7.X versions declare that they work on 0.6, which they do not. It's probably too complicated to both edit METADATA and the repo's REQUIRE file, but this might be a good idea for future versions like #541 .

**Comment by sbromberger** [comment] 2017-03-28 17:39
The thing is, we don't know when LG will break on an unsupported version of Julia. The way we handle this is to be explicit in `README.md` that we support the latest release, but that YMMV on unstables / prereleases, and then we tag a new version that drops support for older releases once we've got fixes. This is what we're planning to do with Julia 0.6 and LG 0.8.

**Comment by tkelman** [comment] 2017-03-28 17:48
Once at least one tagged version is available that does work on nightly, it could make sense to upper-bound all the past tagged versions at whichever first Julia release they won't work on. If there isn't at least one version available without an upper bound, then the package (and all its dependents) won't be installable at all on nightly.

**Comment by iamed2** [comment] 2017-03-28 17:51
@tkelman is it okay to only do that with a PR to METADATA and not go back and edit REQUIRE in the repo?

**Comment by tkelman** [comment] 2017-03-28 17:55
Yes, bounds do need to be updated retroactively once in a while, but sha's should be left alone. For registered packages at a tagged version, the METADATA requires file content takes priority over the package REQUIRE file content.

**Comment by sbromberger** [comment] 2017-03-28 18:06
OK, so I think the plan you're implying is this:

1) merge #541 and followon PRs
2) tag LightGraphs 0.8 (we're moving away from calling it 1.0, btw) with `julia 0.6` in `REQUIRE`
3) open up a PR (or multiple PRs?) in METADATA to fix the previous versions at a given version number

Does that sound right?

**Comment by tkelman** [comment] 2017-03-28 18:10
One PR for adding upper bounds to all the past versions would be preferable. I can help out with that when you're ready. That plan sounds good to me.

**Comment by tkelman** [comment] 2017-03-28 18:11
Though for step 2, what you put as the lower bound of an 0.6-only tag will depend on when it comes out relative to when Julia 0.6.0 final comes out. If you're ready before Julia is, you could set an alpha or rc as your minimum.

**Comment by sbromberger** [comment] 2017-03-28 18:12
Got it. We are ready now, but the issue is that there's really no guarantee that what works on the alpha version will work on the release, right? That seems to argue for putting the alpha version in the LightGraphs 0.8 REQUIRE and making any adjustments necessary when Julia 0.6 is released.

**Comment by sbromberger** [comment] 2017-04-15 15:07
Closing this out in favor of #573 and https://github.com/JuliaLang/METADATA.jl/pull/8817.

**Closed by sbromberger** 2017-04-15 15:07 UTC
