### ISSUE TITLE
PriorityQueue key uniqueness error with a_star

### ISSUE THREAD

**Issue by jhcooperman** [JuliaGraphs/LightGraphs.jl#694] opened 2017-07-19 18:43 UTC
I run into a problem with PriorityQueue key uniqueness when using a_star in the following code. The graph file is attached (and zipped) below.

```
using StatsBase
using LightGraphs

g=loadgraph("examplegraph.jgz")
v=sample(vertices(g), 1, replace=false)
s=v[1]
ans=Array(Int64, 10)
currs=s
i=1
while i < 10
    ans[i]=currs
    i+=1
    nbrs=out_neighbors(g,currs)
    length(nbrs)==0 && break
    nbrs=push!(nbrs,currs)
    currs=trunc(Int,rand(nbrs))
    length(a_star(g,currs,s))
end
```

 I get the following (abridged) error message:

ArgumentError: PriorityQueue keys must be unique
in enqueue! at /Users/sysadmin/.julia/v0.5/DataStructures/src/priorityqueue.jl:190
in a_star_impl! at /Users/sysadmin/.julia/v0.5/LightGraphs/src/shortestpaths/astar.jl:29
in a_star at /Users/sysadmin/.julia/v0.5/LightGraphs/src/shortestpaths/astar.jl:56
in a_star at /Users/sysadmin/.julia/v0.5/LightGraphs/src/shortestpaths/astar.jl:52

I have use a_star extensively in other code with this and similar graphs without any problems.

Thanks.
[examplegraph.jgz.zip](https://github.com/JuliaGraphs/LightGraphs.jl/files/1160110/examplegraph.jgz.zip)

**Comment by sbromberger** [comment] 2017-07-19 18:55
Minimal working example:
```
a_star(g, 9266, 8903)
```

**Comment by sbromberger** [comment] 2017-07-19 18:57
The problem is that you are modifying `out_neighbors` in the line
```
nbrs=push!(nbrs,currs)
```

Docs for `out_neighbors` explicitly warn against this:
```
help?> out_neighbors
search: out_neighbors

  out_neighbors(g, v)

  Return a list of all neighbors connected to vertex v by an outgoing edge.

     Implementation Notes
    ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  Returns a reference, not a copy. Do not modify result.
```

**Comment by sbromberger** [comment] 2017-07-19 19:11
@jhcooperman closing this out, but if you run into further issues, feel free to continue the dialog here.

**Closed by sbromberger** 2017-07-19 19:11 UTC
Labels: not a bug

**Comment by jhcooperman** [comment] 2017-07-20 00:24
Seth,

Thanks for diagnosing my error. I now have the code working. LightGraphs.jl
has been very useful for my research. Thanks again.

Best,
Josh
