### ISSUE TITLE
bug in neighborhood function

### ISSUE THREAD

**Issue by alimamdouh212** [JuliaGraphs/LightGraphs.jl#1363] opened 2020-03-24 20:41 UTC
```
g = SimpleGraph(3)
add_edge!(g, 1, 2)
add_edge!(g, 1, 3)
add_edge!(g, 3, 2)
dismx = zeros((3, 3))
dismx[1, 2] = 10
dismx[1, 3] = 1
dismx[3, 2] = 1
neighborhood(g, 1, 4, dismx)

```
will result in `[1, 3]` despite 2 can be reached from 1 by a path of length 2 .

**Comment by sbromberger** [comment] 2020-03-24 20:55
Possibly related to #1116

**Comment by alimamdouh212** [comment] 2020-03-24 21:10
no, the issue in  #1116 no longer exists.

**Comment by sbromberger** [comment] 2020-03-24 21:19
I know the issue no longer exists, since it was closed in #1166, but the fix that we used there may be the cause or otherwise related.

**Comment by alimamdouh212** [comment] 2020-03-24 21:36
The cause of this issue, is that with the first vist to any node, it
considered visited, and its distance cannot be modified, even if there is
some other path that have shorter distance, but haven't been discovered
yet, the only way to address this isuue is by using Dijkstra's algorithm.

**Comment by alimamdouh212** [comment] 2020-03-24 21:40
Can I submit a PR for it?

**Comment by sbromberger** [comment] 2020-03-24 21:43
It will be fixed once we merge #1332 and migrate neighborhood to use the new shortest paths / traversal code.

**Closed** 2020-03-27 22:38 UTC
Labels: bug
