### ISSUE TITLE
Slow gdistances

### ISSUE THREAD

**Issue by bkamins** [JuliaGraphs/LightGraphs.jl#495] opened 2016-10-30 23:38 UTC
In Julia 0.5 when I found that `gdistances` function was relatively slow. I have manually written BFS finding geodesic distances in `g` from `source` and it is significantly faster than the current implementation. Here is the code and some tests:

```
using LightGraphs

function new_gd(g::SimpleGraph, source)
    n = nv(g)
    dist = fill(-1, n)
    queue = fill(-1, n)
    queue[1] = source
    dist[1] = 0
    head = 1
    tail = 1
    while head <= tail
        current = queue[head]
        distance = dist[current] + 1
        head += 1
        for j in fadj(g, current)
            if dist[j] == -1
                dist[j] = distance
                tail += 1
                queue[tail] = j
            end
        end
    end
    dist
end

function test(size, d)
    g = watts_strogatz(size, d, 0.5)
    r = (@elapsed x2 = gdistances(g, 1)) / (@elapsed x1 = new_gd(g, 1))
    @assert x1 == x2
    lpad(round(r, 2), 7)
end

test(5,1)
for d in [10, 60, 360], i in 0:2
    s = 1000*5^i
    println("graph size $(lpad(s, 5)) and avg. degree $(lpad(d, 3)): $(test(s, d))")
end
```

The relative speedups are:

```
graph size  1000 and avg. degree  10:   558.1
graph size  5000 and avg. degree  10:   33.72
graph size 25000 and avg. degree  10:   32.89
graph size  1000 and avg. degree  60:   70.34
graph size  5000 and avg. degree  60:   59.55
graph size 25000 and avg. degree  60:   51.31
graph size  1000 and avg. degree 360:  161.21
graph size  5000 and avg. degree 360:  144.11
graph size 25000 and avg. degree 360:  115.99
```

Do I miss something important in implementation of `gdistances` that is not covered in implementation of `new_gd` (the current implementation assumes that `source` is a single vertex but it can be simply extended)?

**Comment by sbromberger** [comment] 2016-10-30 23:44
Well, are we sure they're equivalent?

```
julia> g = smallgraph(:tutte)
{46, 69} undirected graph

julia> a = gdistances(g,3);

julia> b = new_gd(g,3);

julia> a == b
false
```

**Comment by bkamins** [comment] 2016-10-31 00:02
@sbromberger you are correct. I have copy-pasted wrong code I was experimenting with. Here is correct code:
```
function new_gd(g::SimpleGraph, source)
    n = nv(g)
    dist = fill(-1, n)
    queue = fill(-1, n)
    queue[1] = source
    dist[source] = 0
    head = 1
    tail = 1
    while head <= tail
        current = queue[head]
        distance = dist[current] + 1
        head += 1
        for j in fadj(g, current)
            if dist[j] == -1
                dist[j] = distance
                tail += 1
                queue[tail] = j
            end
        end
    end
    dist
end
```

**Comment by bkamins** [comment] 2016-10-31 00:03
I mistakenly set `dist[1]=0` instead of `dist[source]=0`

**Comment by sbromberger** [comment] 2016-10-31 00:14
That'd do it :)

Anyway - at first glance your code is much more efficient, even with preallocated distance matrices:

```
julia> @time a = gdistances(g,3);
  5.226759 seconds (64.98 M allocations: 1.219 GB, 4.31% gc time)

julia> @time b = new_gd(g,3);
  0.643095 seconds (8 allocations: 15.259 MB, 2.92% gc time)

julia> dists = fill(0, nv(g));

julia> @time a = gdistances!(g,3,dists);
  5.345857 seconds (64.98 M allocations: 1.212 GB, 3.92% gc time)

If you wanted to put together a PR that replaced `gdistances` and `gdistances!` with your code, we'd certainly put it through its paces and adopt it if we didn't see any regressions. You'd need to allow for multiple sources, though.

**Comment by sbromberger** [comment] 2016-10-31 00:18
Well, hold on a sec. This was changed in https://github.com/JuliaGraphs/LightGraphs.jl/commit/c571fdfdf9bee2a01c15dc989cdebfe750a9211f - let me see what happened before then.

**Comment by jpfairbanks** [comment] 2016-11-29 01:21
Can this be closed since #496 was merged?

**Comment by bkamins** [comment] 2016-12-01 09:49
@sbromberger The current solution is of course acceptable for me :). I do not know what is your policy who should close the issue (me or LightGraphs member).

And in general thank you again for your work. I am using LightGraphs in my research and it is fantastic.

**Comment by jpfairbanks** [comment] 2016-12-01 13:59
Thanks for the sign-off and the endorsement! Do you have a name and website for your research projects that use LG? We should curate a list of satisfied users.

**Comment by bkamins** [comment] 2016-12-01 14:09
When it goes public I will let you know. Thanks.

**Comment by sbromberger** [comment] 2016-12-04 21:18
I'm gonna close this out - feel free to continue discussion though. If we need to reopen it, just let me know.

**Closed by sbromberger** 2016-12-04 21:18 UTC
