### ISSUE TITLE
Tag the latest version 

### ISSUE THREAD

**Issue by mdpradeep** [JuliaGraphs/LightGraphs.jl#339] opened 2016-04-20 08:41 UTC
The tagged version of LightGraphs.jl fails while doing "using LightGraphs" because of pre-compilation. I believe that this is fixed with the latest version. Can the latest version be tagged ?

**Comment by sbromberger** [comment] 2016-04-20 11:53
Could you post the error?

**Comment by mdpradeep** [comment] 2016-04-20 17:57
Here's the error. But this could be because of bringing several other packages (before this) in to workspace. Will get back after some more investigation.

```
WARNING: Module Clustering uuid did not match cache file
ERROR: LoadError: __precompile__(true) but require failed to create a precompile
d cache file
in require at loading.jl:252
[inlined code] from C:\\\\\\\\\\\\\\\\\Users\andy\AppData\Local\JuliaPro\0.1.0\
JuliaPackages\v0.4\Requires\src\require.jl:11
in require at C:\\\\\\\\\\\\\\\\\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaP
ackages\v0.4\Requires\src\hook.jl:17
in include at boot.jl:261
in include_from_node1 at loading.jl:304
while loading C:\Users\andy\Documents\quantecon_postinstallscript.jl, in express
ion starting on line 113
```

**Comment by jpfairbanks** [comment] 2016-04-20 18:05
Can you `using Clustering` in an otherwise blank repl?

**Comment by sbromberger** [comment] 2016-04-21 00:20
If you remove the Clustering.ji cache file, does it work?

**Comment by mdpradeep** [comment] 2016-04-21 12:54
@AndyGreenwell - Could you please comment on the above ?

**Comment by AndyGreenwell** [comment] 2016-04-21 13:22
The problem was related to attempting to perform `Pkg.add("LightGraphs")` and `using LightGraphs` prior to performing `Pkg.add` and `using` on some other packages that include LightGraphs (and Requires.jl) as a dependency within their REQUIRE files in association with a particular distribution of Julia being created that comes prepackaged with a large number of packages that have already been precompiled.  

LightGraphs makes use of the [Requires.jl](https://github.com/MikeInnes/Requires.jl) package, and the functionality of Requires.jl does not always play well with precompilation or existing precompiled packages.  

Ultimately I was able to work around the error above by ensuring that in the script I wrote to install extra packages on top of this particular Julia distribution (with its existing set of precompiled packages) the top package that would ultimately have LightGraphs (and Requires) as one of its dependencies was added and imported with `Pkg.add` and `using`, but LightGraphs itself and any intermediate packages that have LightGraphs (and Requires) as a dependency were not explicitly added and imported with `Pkg.add` and `using` statements.

**Comment by sbromberger** [comment] 2016-04-21 14:11
@AndyGreenwell @mdpradeep While I don't doubt that Requires.jl probably has some issues, it does not appear to be related to the error message above, since Clustering is explicitly listed in `REQUIRE`.

The error message above appears to be related to QuantEcon, which uses LightGraphs, but I'm not really seeing the connection to LG from that error message. Could you clarify where you believe the issue to be? We'd like to fix it, especially if it's causing people to have difficulty installing other packages.

@jpfairbanks - we need to take a(nother) look at the general issue of package fragility in Julia.

**Comment by AndyGreenwell** [comment] 2016-04-21 15:09
@sbromberger In my some testing I was performing with this particular distribution of Julia (not currently public) that comes with a set of existing precompiled packages, below is an example of a few operations that resulted in this error.

The commands added to a newly installed Julia (that includes this pre-built set of precompiled packages) are as follows:
```julia
Pkg.add("Clustering")
using Clustering
Pkg.add("LightGraphs")
using LightGraphs
```

Output is the following:

```               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("Clustering")
INFO: Cloning cache of Clustering from git://github.com/JuliaStats/Clustering.jl.git
INFO: Installing Clustering v0.5.0
INFO: Package database updated
INFO: METADATA is out-of-date - you may not have the latest version of Clustering
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> using Clustering

julia> Pkg.add("LightGraphs")
INFO: Cloning cache of AutoHashEquals from git://github.com/andrewcooke/AutoHashEquals.jl.git
INFO: Cloning cache of Combinatorics from git://github.com/JuliaLang/Combinatorics.jl.git
INFO: Cloning cache of LightGraphs from git://github.com/JuliaGraphs/LightGraphs.jl.git
INFO: Cloning cache of LightXML from git://github.com/JuliaLang/LightXML.jl.git
INFO: Cloning cache of ParserCombinator from git://github.com/andrewcooke/ParserCombinator.jl.git
INFO: Installing AutoHashEquals v0.0.9
INFO: Installing Combinatorics v0.2.0
INFO: Installing LightGraphs v0.5.2
INFO: Installing LightXML v0.2.1
INFO: Installing ParserCombinator v1.7.8
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/86aaf8e1aa008aa3239ca48ba0fbdecada44a122e85c79bf1863e9fdd417655a-primary.xml.gz
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repos
itories/windows:/mingw:/win64/openSUSE_13.2/repodata/d2630cfb02919d1428ddd0e73684907045f9cf205ba948a7188881c2ad596c6b-primary.xml.gz
INFO: Building Blosc
INFO: Building HDF5
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building LightXML
INFO: Packages to update:  zlib1
INFO: Packages to install: libxml2-2
INFO: Downloading: zlib1
INFO: Extracting: zlib1
INFO: Downloading: libxml2-2
INFO: Extracting: libxml2-2
INFO: Complete
INFO: Package database updated
INFO: METADATA is out-of-date - you may not have the latest version of LightGraphs
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> using LightGraphs
INFO: Precompiling module LightGraphs...
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\HDF5.ji for module HDF5.
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\JLD.ji for module JLD.
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\LightGraphs.ji for module LightGraphs.
WARNING: Module Clustering uuid did not match cache file
ERROR: __precompile__(true) but require failed to create a precompiled cache file
 in require at loading.jl:252
```

Next, after installing this same version of Julia again in fresh operating system image, performing a similar test where I add, load, and precompile LIghtGraphs prior to QuantEcon.

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("LightGraphs")
INFO: Cloning cache of AutoHashEquals from git://github.com/andrewcooke/AutoHashEquals.jl.git
INFO: Cloning cache of Clustering from git://github.com/JuliaStats/Clustering.jl.git
INFO: Cloning cache of Combinatorics from git://github.com/JuliaLang/Combinatorics.jl.git
INFO: Cloning cache of LightGraphs from git://github.com/JuliaGraphs/LightGraphs.jl.git
INFO: Cloning cache of LightXML from git://github.com/JuliaLang/LightXML.jl.git
INFO: Cloning cache of ParserCombinator from git://github.com/andrewcooke/ParserCombinator.jl.git
INFO: Installing AutoHashEquals v0.0.9
INFO: Installing Clustering v0.5.0
INFO: Installing Combinatorics v0.2.0
INFO: Installing LightGraphs v0.5.2
INFO: Installing LightXML v0.2.1
INFO: Installing ParserCombinator v1.7.8
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/86aaf8e1aa008aa3239ca48ba0fbdecada44a122e85c79bf1863e9fdd417655a-primary.xml.gz
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/d2630cfb02919d1428ddd0e7368
4907045f9cf205ba948a7188881c2ad596c6b-primary.xml.gz
INFO: Building Blosc
INFO: Building HDF5
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building LightXML
INFO: Packages to update:  zlib1
INFO: Packages to install: libxml2-2
INFO: Downloading: zlib1
INFO: Extracting: zlib1
INFO: Downloading: libxml2-2
INFO: Extracting: libxml2-2
INFO: Complete
INFO: Package database updated
INFO: METADATA is out-of-date - you may not have the latest version of LightGraphs
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> using LightGraphs
INFO: Precompiling module LightGraphs...
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\HDF5.ji for module HDF5.
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\JLD.ji for module JLD.

julia> Pkg.add("QuantEcon")
INFO: Cloning cache of DSP from git://github.com/JuliaDSP/DSP.jl.git
INFO: Cloning cache of QuantEcon from git://github.com/QuantEcon/QuantEcon.jl.git
INFO: Installing DSP v0.0.11
INFO: Installing QuantEcon v0.4.2
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building Blosc
INFO: Building HDF5
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building LightXML
INFO: Nothing to do
INFO: Package database updated
INFO: METADATA is out-of-date - you may not have the latest version of QuantEcon

INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> using QuantEcon
INFO: Precompiling module QuantEcon...
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\HDF5.ji for module HDF5.
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\LightGraphs.ji for module LightGraphs.
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\JLD.ji for module JLD.
INFO: Recompiling stale cache file C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\QuantEcon.ji for module QuantEcon.
WARNING: Module LightGraphs uuid did not match cache file
ERROR: __precompile__(true) but require failed to create a precompiled cache file
 in require at loading.jl:252
 [inlined code] from C:\\\\\\\\\\\\\\\\\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\v0.4\Requires\src\require.jl:11
 in require at C:\\\\\\\\\\\\\\\\\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\v0.4\Requires\src\hook.jl:17

julia>
```

I will also perform this same test on a version of Julia downloaded directly from www.julialang.org wherein all precompilation of all packages (and tracking of all of that precompilation) being performed occurs directly on the same machine as where the same installation is present, not as part of a pre-existing build process.

**Comment by AndyGreenwell** [comment] 2016-04-21 15:28
Here is the behavior of the same test using a version of Julia 0.4.3 that was previously obtained directly from www.julialang.org/downloads, and in which the operational environment did not have any existing packages present.  

Essentially the same behavior is observed wherein the order in which packages are added, precompiled, added, and precompiled affects later precompilation.  Thus far, I have only observed this effect for packages making use of Requires.jl, but I will investigate other cases as well.

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("Clustering")
INFO: Initializing package repository C:\Users\andy\.julia\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of Clustering from git://github.com/JuliaStats/Clustering.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Distances from git://github.com/JuliaStats/Distances.jl.git
INFO: Cloning cache of StatsBase from git://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of StatsFuns from git://github.com/JuliaStats/StatsFuns.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing Clustering v0.5.0
INFO: Installing Compat v0.7.13
INFO: Installing Distances v0.3.0
INFO: Installing StatsBase v0.8.0
INFO: Installing StatsFuns v0.2.0
INFO: Package database updated

julia> using Clustering
INFO: Precompiling module ArrayViews...
INFO: Precompiling module Distances...
INFO: Precompiling module StatsBase...

julia> Pkg.add("LightGraphs")
INFO: Cloning cache of AutoHashEquals from git://github.com/andrewcooke/AutoHashEquals.jl.git
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Blosc from git://github.com/stevengj/Blosc.jl.git
INFO: Cloning cache of Combinatorics from git://github.com/JuliaLang/Combinatorics.jl.git
INFO: Cloning cache of Docile from git://github.com/MichaelHatherly/Docile.jl.git
INFO: Cloning cache of FileIO from git://github.com/JuliaIO/FileIO.jl.git
INFO: Cloning cache of GZip from git://github.com/JuliaLang/GZip.jl.git
INFO: Cloning cache of HDF5 from git://github.com/JuliaLang/HDF5.jl.git
INFO: Cloning cache of Iterators from git://github.com/JuliaLang/Iterators.jl.git
INFO: Cloning cache of JLD from git://github.com/JuliaLang/JLD.jl.git
INFO: Cloning cache of LibExpat from git://github.com/amitmurthy/LibExpat.jl.git
INFO: Cloning cache of LightGraphs from git://github.com/JuliaGraphs/LightGraphs.jl.git
INFO: Cloning cache of LightXML from git://github.com/JuliaLang/LightXML.jl.git
INFO: Cloning cache of MacroTools from git://github.com/one-more-minute/MacroTools.jl.git
INFO: Cloning cache of ParserCombinator from git://github.com/andrewcooke/ParserCombinator.jl.git
INFO: Cloning cache of Polynomials from git://github.com/Keno/Polynomials.jl.git
INFO: Cloning cache of Requires from git://github.com/one-more-minute/Requires.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of WinRPM from git://github.com/JuliaLang/WinRPM.jl.git
INFO: Cloning cache of Zlib from git://github.com/dcjones/Zlib.jl.git
INFO: Installing AutoHashEquals v0.0.9
INFO: Installing BinDeps v0.3.21
INFO: Installing Blosc v0.1.4
INFO: Installing Combinatorics v0.2.0
INFO: Installing Docile v0.5.23
INFO: Installing FileIO v0.0.4
INFO: Installing GZip v0.2.18
INFO: Installing HDF5 v0.5.8
INFO: Installing Iterators v0.1.9
INFO: Installing JLD v0.5.9
INFO: Installing LibExpat v0.1.2
INFO: Installing LightGraphs v0.5.2
INFO: Installing LightXML v0.2.1
INFO: Installing MacroTools v0.3.0
INFO: Installing ParserCombinator v1.7.8
INFO: Installing Polynomials v0.0.5
INFO: Installing Requires v0.2.2
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.3
INFO: Installing WinRPM v0.1.15
INFO: Installing Zlib v0.1.12
INFO: Building Blosc
INFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/86aaf8e1aa008aa3239ca48ba0fbdecada44a122e85c79bf1863e9fdd417655a-primary.xml.gz
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/d2630cfb02919d1428ddd0e73684907045f9cf205ba948a7188881c2ad596c6b-primary.xml.gz
INFO: Building HDF5
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Packages to install: zlib1, hdf5
INFO: Downloading: zlib1
INFO: Extracting: zlib1
INFO: Downloading: hdf5
INFO: Extracting: hdf5
INFO: Complete
INFO: Building LightXML
INFO: Packages to install: libxml2-2
INFO: Downloading: libxml2-2
INFO: Extracting: libxml2-2
INFO: Complete
INFO: Package database updated

julia> using LightGraphs
INFO: Precompiling module LightGraphs...
INFO: Recompiling stale cache file C:\Users\andy\.julia\lib\v0.4\LightGraphs.ji for module LightGraphs.
WARNING: Module Clustering uuid did not match cache file
ERROR: __precompile__(true) but require failed to create a precompiled cache file
 in require at loading.jl:252

julia>
```

**Comment by jpfairbanks** [comment] 2016-04-21 15:33
Are the compilation outputs "*.ji files" supposed to be portable? As in, compile on one machine run on another?

**Comment by sbromberger** [comment] 2016-04-21 15:34
It really looks like `C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\lib\v0.4\` is not empty. Can you clean that dir and remove all packages except for METADATA from C:\Users\andy\AppData\Local\JuliaPro\0.1.0\JuliaPackages\v0.4`, and then do a `Pkg.update()` followed by a `Pkg.add("LightGraphs")`?

**Comment by jpfairbanks** [comment] 2016-04-21 15:37
Also are you able to acutally use Clustering after you load it with using
or Pkg.test("Clustering")?

**Comment by AndyGreenwell** [comment] 2016-04-21 15:41
The test in my most recent [comment](https://github.com/JuliaGraphs/LightGraphs.jl/issues/339#issuecomment-212974172) above occurs in an environment where there were no pre-existing Julia packages and all precompilation occurs on the same machine. The directory `C:\Users\andy\.julia\v0.4\` did not exist prior to the first `Pkg.add` command added to that session.  So this is a test that anyone should be able to reproduce. 

In that particular environment, `Pkg.test("Clustering")` completes successfully with the following output:
```
julia> Pkg.test("Clustering")
INFO: Testing Clustering
Runing tests:
* seeding.jl ...
* kmeans.jl ...
* kmedoids.jl ...
* affprop.jl ...
* dbscan.jl ...
* silhouette.jl ...
* varinfo.jl ...
* randindex.jl ...
* hclust.jl ...
INFO: Clustering tests passed
```

**Comment by sbromberger** [comment] 2016-04-21 15:44
So, I'm a bit confused (perhaps because I haven't had my caffeine yet), but in our REQUIRE, we have

```
Clustering 0.4
```

But at https://github.com/JuliaStats/Clustering.jl/tags, I only see up to v0.3.3.

What gives?

**Comment by AndyGreenwell** [comment] 2016-04-21 16:15
With regards to visible tag versions on GitHub, maybe the package authors are not always pushing their tags?

Something like the following situation:

http://www.thisprogrammingthing.com/2013/git-tags-not-showing-in-github/

**Comment by sbromberger** [comment] 2016-04-21 16:17
Yeah. I opened up an issue to ask about that. `Pkg.tag()` should do this, I think - that's how we're getting tags in LightGraphs - but perhaps Clustering is using a different release process.

**Comment by sbromberger** [comment] 2016-04-21 16:24
I'm getting the same failure but with a different warning:

```
WARNING: Module Clustering uuid did not match cache file
  This is likely because module Clustering does not support  precompilation but is imported by a module that does.
```

**Comment by AndyGreenwell** [comment] 2016-04-21 16:38
I posted the failure from an installation of Julia 0.4.3, which is the same version currently present in that "special" build for which the initial terminal screen scrapes were produced.

You are likely using a more recent release of Julia.

**Comment by sbromberger** [comment] 2016-04-27 18:03
Not sure this fixes the underlying issue, but I just tagged 0.5.3. Closing out for now.

**Closed by sbromberger** 2016-04-27 18:03 UTC
