### ISSUE TITLE
Rename Simple[Di]GraphFromIterator for v2.0

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaGraphs/LightGraphs.jl#1411] opened 2020-04-28 20:26 UTC
The name `Simple[Di]GraphFromIterator` implies that you are constructing an object of type `Simple[Di]GraphFromIterator`, but they in fact return objects of type `Simple[Di]Graph`. So, it seems like those functions should either be renamed to `Simple[Di]Graph`, or perhaps to something like `simple_[di]graph`.

**Comment by sbromberger** [comment] 2020-04-28 20:33
The problem is that there is no generic type for an iterator, and we don't really want to have an untyped constructor that assumes iteration, since that becomes the default.

**Comment by sbromberger** [comment] 2020-04-28 20:35
```
function typechain(x)
    T = typeof(x)
    println(T)
    while T != Any
        T = supertype(T)
        println(T)
    end
end
```
```
julia> typechain(edges(g))
LightGraphs.SimpleGraphsCore.SimpleEdgeIter{SimpleGraph{Int64}}
AbstractEdgeIter
Any
```

**Comment by CameronBieganek** [comment] 2020-04-28 20:44
Hmm, I don't know what your current state of development on the 2.0 branch is, but on v1.3.2, the method table looks like this:

```julia
julia> methods(SimpleGraph)
# 11 methods for type constructor:
[1] (::Type{SimpleGraph})() in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:50
[2] (::Type{SimpleGraph})(n::T) where T<:Integer in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:47
[3] (::Type{SimpleGraph})(::Type{T}) where T<:Integer in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:64
[4] (::Type{SimpleGraph})(edge_list::Array{LightGraphs.SimpleGraphs.SimpleEdge{T},1}) where T<:Integer in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:205
[5] (::Type{SimpleGraph})(adjmx::AbstractArray{T,2} where T) in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:85
[6] (::Type{SimpleGraph})(g::SimpleGraph) in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:115
[7] (::Type{SimpleGraph})(g::SimpleDiGraph) in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:141
[8] (::Type{SimpleGraph})(nv::T, ne::Integer; seed) where T<:Integer in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/generators/randgraphs.jl:42
[9] (::Type{SimpleGraph})(nvg::Integer, neg::Integer, edgestream::Channel) in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/generators/randgraphs.jl:1030
[10] (::Type{SimpleGraph})(nvg::Integer, neg::Integer, sbm::StochasticBlockModel) in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/generators/randgraphs.jl:1046
[11] (::Type{SimpleGraph})(ne, fadjlist::Array{Array{T,1},1}) where T in LightGraphs.SimpleGraphs at /Users/bieganek/.julia/packages/LightGraphs/XeHqk/src/SimpleGraphs/simplegraph.jl:23
```

So, all of the existing methods are more specific than `SimpleGraph(iter)`, so it seems like you could get away with renaming `SimpleGraphFromIterator` to `SimpleGraph`. (At least on v1.3.2, and ignoring the fact that it's a breaking change.)

Otherwise I would suggest a snake case name like `simple_graph` or `simple_graph_from_iterator`, since the convention that `CamelCase()` produces an object of type `CamelCase` is very strong in Julia.

By the way, thank you for all of your hard work on LightGraphs! It's a great package.

**Comment by simonschoelly** [comment] 2020-04-28 20:51
If I remember correctly, when I implemented this constructor, there were some issues, because we also had a constructor that accepted a matrix.

Maybe it is time to reconsider that for 2.0. Currently we have way too many constructors for my taste, which makes deliverability difficult, but maybe the Erdos-Renyi constructors will go away with 2.0. On the other hand we will introduce there some new constructors so I don't know.

Maybe we would also do something with kwargs? Like
```
SimpleGraph(; from_iterator) = ...
```
I am currently not sure if that is actually possible though.

**Comment by sbromberger** [comment] 2020-04-28 20:52
If you did that, and created `SimpleGraph(iter)`, then it would be used for ALL `iters` that didn't match another constructor type, regardless of whether `iter` was actually an iter. An example would be `SimpleGraph("hello")`, which wouldn't produce a method error, but some other error deep in the bowels of the constructor. This is not a great user experience.

**Comment by sbromberger** [comment] 2020-04-28 21:03
... and fwiw I agree that we have way too many constructors.

**Comment by CameronBieganek** [comment] 2020-04-28 21:12
There are plenty of functions in Base with a generic `itr` method. Examples:

- [sum](https://github.com/JuliaLang/julia/blob/b8e9a9ecc62ab49003bd4f1834771bdeb8cb1aa2/base/reduce.jl#L503)
- [mean](https://github.com/JuliaLang/Statistics.jl/blob/a87c385b812e6576be984cae96beae64252214f0/src/Statistics.jl#L44)

And they have the property you mentioned where you can feed them an arbitrary iterator and end up with an error from somewhere inside the function:

```julia
julia> sum("hello")
ERROR: MethodError: no method matching +(::Char, ::Char)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:529
  +(::Integer, ::AbstractChar) at char.jl:224
  +(::T, ::Integer) where T<:AbstractChar at char.jl:223
Stacktrace:
 [1] add_sum(::Char, ::Char) at ./reduce.jl:21
 [2] BottomRF at ./reduce.jl:78 [inlined]
 [3] _foldl_impl(::Base.BottomRF{typeof(Base.add_sum)}, ::Base._InitialValue, ::String) at ./reduce.jl:59
 [4] foldl_impl at ./reduce.jl:45 [inlined]
 [5] mapfoldl_impl at ./reduce.jl:41 [inlined]
 [6] #mapfoldl#189 at ./reduce.jl:157 [inlined]
 [7] mapfoldl at ./reduce.jl:157 [inlined]
 [8] #mapreduce#193 at ./reduce.jl:283 [inlined]
 [9] mapreduce at ./reduce.jl:283 [inlined]
 [10] sum at ./reduce.jl:486 [inlined]
 [11] sum(::String) at ./reduce.jl:503
 [12] top-level scope at REPL[146]:1

julia> mean("hello")
ERROR: MethodError: no method matching +(::Char, ::Char)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:529
  +(::Integer, ::AbstractChar) at char.jl:224
  +(::T, ::Integer) where T<:AbstractChar at char.jl:223
Stacktrace:
 [1] mean(::typeof(identity), ::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Statistics/src/Statistics.jl:70
 [2] mean(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Statistics/src/Statistics.jl:42
 [3] top-level scope at REPL[147]:1
```

At some point you have to put some level of responsibility on the user not to do something silly like `SimpleGraph("hello")`.

**Comment by sbromberger** [comment] 2020-04-28 21:21
fair enough, but then you run into the problem of the type of iterable. In this case, we're saved because we actually have a type of iterator, called `AbstractEdgeIter`, which is really all this function accepts anyway. So we could create a specialized method for `AbstractEdgeIter`.

**Comment by sbromberger** [comment] 2020-04-28 21:22
although if we're zipping things, it won't work.

**Comment by CameronBieganek** [comment] 2020-04-28 21:36
Sorry, I'm ignorant of the details of `AbstractEdgeIter`, but could you add `first` and `last` methods to `Edge` so that you could write a generic `SimpleGraph(itr)` constructor that would work for an iterator over `Edge`s, pairs, and length 2 tuples or arrays? Or, alternatively you could add a `getindex` method to `Edge` so that you can do `e = Edge(4, 5); e[1]`.

Just brainstorming here. I don't know if there's a real need to be able to construct graphs from an iterator of pairs or tuples. On the other hand, that does seem like a use case that somebody will want at some point. :)

**Comment by sbromberger** [comment] 2020-04-28 22:09
if we're going to be eliminating constructors, I'd say that we should let people write what they need. :) The number of constructors in 2.0 has ballooned to over 40 (randgraphs, smallgraphs, etc). I think we need to figure out which legacy ones we should get rid of. There are a few, but the issue is type parameterization requires two per. That is,

```
function SimpleGraph{T}(n::Integer=0)
....
end
SimpleGraph(n::T) where {T<:Integer} = SimpleGraph{T}(n)
```

**Comment by CameronBieganek** [comment] 2020-06-29 17:43
Not sure if this should be marked as stale...

**Comment by sbromberger** [comment] 2020-06-29 17:55
agreed.

**Comment by CameronBieganek** [comment] 2020-08-29 22:17
stale bot bump

**Comment by CameronBieganek** [comment] 2020-12-25 15:06
.

**Comment by sbromberger** [comment] 2021-02-18 14:15
Given that the 2.0 plans have changed a bit, I'm not sure we're going to get to this in the near future unless someone wants to make a PR. I'll close it out for now.

**Closed by sbromberger** 2021-02-18 14:15 UTC
Labels: 1.4.0/2.0.0, decision, discussion
