### ISSUE TITLE
Problems reading a xml graph

### ISSUE THREAD

**Issue by cndesantana** [JuliaGraphs/LightGraphs.jl#94] opened 2015-07-17 22:24 UTC
Hi,

I am new in LightGraphs.jl. It seems to be a great library when our graph files and our needs fit with the library's features. 

I am trying to read a simple xml graph that was created using Julia + PyCall + python-Igraph (command write_graphml(file) - http://igraph.org/python/doc/igraph-pysrc.html#GraphBase.write_graphml) . 

I have Julia 0.4.0-dev+5920 (2015-07-10) and LightGraphs.jl installed. I am using the following commands:

> using LightGraphs
> net1 = readgraphml("network.xml")

And I got the following error:
ERROR: Unknown node key
 in error at ./error.jl:21
 in readgraphml at /home/cdesantana/.julia/v0.4/LightGraphs/src/persistence.jl:106

I couldn't find anything about this error in other forums. 

In file persistence.jl the error corresponds to the following piece of code:

            if name(e) == "graph"
                nodes = Dict{String,Int}()
                edges = @compat Tuple{Int, Int}[]
                graphname = has_attribute(e, "id") ? attribute(e, "id") : nothing
                edgedefault = attribute(e, "edgedefault")
                isdirected = edgedefault=="directed" ? true :
                             edgedefault=="undirected" ? false : error("Unknown value of edgedefault: $edgedefault")
            else
                error("Unknown node $(name(e))")
            end

Does it mean that my XML file is bad? The file is here: https://github.com/cndesantana/filestoshare/blob/master/network.xml 

If so, what is the best way to generate an XML file to be read by LightGraphs.jl?

Thanks for your attention! Sorry the large message.

Charles

**Comment by sbromberger** [comment] 2015-07-17 22:31
Hi,

So - this graph file represents a multigraph, which isn't supported in LightGraphs. In addition, I don't know  that non-integer nodes are recognized in our parser right now. The latter can be fixed; the former can't be.

**Comment by sbromberger** [comment] 2015-07-17 22:38
Also: if you get rid of ` <key id="v_name" for="node" attr.name="name" attr.type="string"/>` in the graphml file, you should see this working. I've confirmed that non-integer node id's are fine, but because this is a multigraph, you're going to get an error like this:

```
ERROR: Edge edge 2 - 6 is already in graph
```

That's because you have two of these in your xml:

```
<edge source="n1" target="n5">
```

**Comment by cndesantana** [comment] 2015-07-17 22:39
Hi Seth, 

Thank you very much for your quick and clear response. 

I can try to generate a weighted graph instead of multigraph. In such a case the weight of each edge would be the number of repetitions of the edge in the original multigraph. 

I will do it and try again with LightGraphs.jl. I will let you know if it works.

Thank you for your attention! Have a nice weekend!

**Comment by sbromberger** [comment] 2015-07-17 22:41
@cndesantana ok - note that LightGraphs doesn't "store" edge weights - it leaves that to you. I would recommend using a backend datastore if you've got a large graph, or a simple {Edge, Int} dict if you want to keep them all in memory.

**Comment by cndesantana** [comment] 2015-07-17 22:46
@sbromberger good point. Thanks for the advice! I will need to think better about this workaround you mention. I guess we will need to test it against other options (maybe using Graphs.jl or, in worst case, python-igraph). I will let you know anyway. thanks for everything! ;)

**Comment by cndesantana** [comment] 2015-07-17 22:49
By the way, I just saw your message in Julia-users mailing list about the GML parser. It is amazing!! I will take a look at it! :) Thanks!!

Best

**Comment by sbromberger** [comment] 2015-07-17 23:00
Just FYI - I fixed the abend when readgraphml() encounters an unknown node (the "key" error you got earlier), and made some other minor improvements. I put it in the "gml" branch if you'd like to try it.

**Comment by sbromberger** [comment] 2015-07-21 16:57
Closing this out because the unknown node issue is resolved (fix is in `gml`).

**Closed** 2015-07-21 16:58 UTC
