### ISSUE TITLE
LoadError: UndefVarError: add_edge! not defined 

### ISSUE THREAD

**Issue by Chathanee** [JuliaGraphs/LightGraphs.jl#662] opened 2017-06-19 12:19 UTC
The following code is exactly similar to the example given in Flow and Cut in LightGraphs documentation. 

`for k in flow_edges
  u, v, f = k
  add_edge!(flow_graph, u, v)
  capacity_matrix[u,v] = f
end`

It was working smoothly until yesterday, but it is not working now and I'm getting an error message as 
`LoadError: UndefVarError: add_edge! not defined `

**Comment by sbromberger** [comment] 2017-06-19 12:36
What version of Julia / LightGraphs are you using?

**Comment by Chathanee** [comment] 2017-06-19 12:42
Julia - Version 0.5.1
LightGraphs - v 0.7.7

**Comment by sbromberger** [comment] 2017-06-19 12:49
No changes to 0.7.7 have been made for a while. Are you sure you've done a `using LightGraphs` prior to calling `add_edge!`?

**Comment by Chathanee** [comment] 2017-06-19 12:55
Yes, I'm using the same example given in the documentation. It was nicely working until yesterday. But when I check it now, it gives me the above error.  

```
LoadError: UndefVarError: add_edge! not defined
while loading /Users/xxx/xxx/ip.jl, in expression starting on line 75
 in macro expansion; at ip.jl:77 [inlined]
 in anonymous at <missing>:?
 in include_string(::String, ::String) at loading.jl:441
 in include_string(::String, ::String) at sys.dylib:?
 in include_string(::Module, ::String, ::String) at Compat.jl:1492
 in (::Atom.##59#62{String,String})() at eval.jl:73
 in withpath(::Atom.##59#62{String,String}, ::String) at utils.jl:30
 in withpath(::Function, ::String) at eval.jl:38
 in macro expansion at eval.jl:71 [inlined]
 in (::Atom.##58#61{Dict{String,Any}})() at task.jl:60

```

**Comment by sbromberger** [comment] 2017-06-19 12:55
Also, are there any other warnings? Is some other package conflicting with `add_edge!`?

**Comment by Chathanee** [comment] 2017-06-19 12:58
Nope!!! I'm using only LightGraphs and Graphs packages for my model. I didn't get any other error messages which tells about other packages.

**Comment by sbromberger** [comment] 2017-06-19 13:45
That's probably the problem. Both Graphs and LightGraphs export `add_edge!` so there's going to be a method conflict.

**Comment by sbromberger** [comment] 2017-06-19 13:54
```
julia> using LightGraphs

julia> g = Graph(10)
{10, 0} undirected graph

julia> add_edge!(g,1,2)
true
```

but

```
julia> using Graphs
WARNING: Method definition (::Type{Graphs.KeyVertex})(Int64, #K<:Any) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:12 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:16.
WARNING: Method definition (::Type{Graphs.Edge})(Int64, #V<:Any, #V<:Any) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:54 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:60.
WARNING: Method definition (::Type{Graphs.ExEdge})(Int64, #V<:Any, #V<:Any, Base.Dict{String, Any}) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:72 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:83.
WARNING: Method definition (::Type{Graphs.TargetIterator})(#G<:Graphs.AbstractGraph, #EList<:Any) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:123 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:127.
WARNING: Method definition (::Type{Graphs.SourceIterator})(#G<:Graphs.AbstractGraph, #EList<:Any) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:141 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:145.
WARNING: Method definition edge_property_requirement(Graphs.AbstractEdgePropertyInspector{#T<:Any}, Graphs.AbstractGraph{#V<:Any, E<:Any}) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:164 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/common.jl:179.
WARNING: Method definition vertex_index(#V<:Union{Graphs.ExVertex, Graphs.KeyVertex}, Graphs.GenericGraph{#V<:Union{Graphs.ExVertex, Graphs.KeyVertex}, E<:Any, VList<:Any, EList<:Any, IncList<:Any}) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/graph.jl:65 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/graph.jl:67.
WARNING: Method definition (::Type{Graphs.GDistanceVisitor})(#G<:Graphs.AbstractGraph, #DMap<:Any) in module Graphs at /Users/bromberger1/.julia/v0.5/Graphs/src/breadth_first_visit.jl:107 overwritten at /Users/bromberger1/.julia/v0.5/Graphs/src/breadth_first_visit.jl:111.

julia> add_edge!
WARNING: both Graphs and LightGraphs export "add_edge!"; uses of it in module Main must be qualified
ERROR: UndefVarError: add_edge! not defined
```

**Comment by Chathanee** [comment] 2017-06-19 14:00
Thanks! But I tried it after commenting "using Graphs" too. But still the same error is coming. 
It comes even when running the same example in a new file without other codes. What can we do for that? 
Also if we comment "using Graphs " there are some dependency issues in the code.

**Comment by juliohm** [comment] 2017-06-19 14:02
@Chathanee any specific reason to use `Graphs.jl`?

Can you share the latest code snippet that is throwing an error in your setup?

**Comment by Chathanee** [comment] 2017-06-19 14:06
I'm trying to create a graph and some of the parts in the code  need the package graphs.jl. 

I'm using the same flow and cut example to check the maxflow between nodes. It was working nicely until yesterday.

**Comment by sbromberger** [comment] 2017-06-19 14:06
There's generally no good reason to use both Graphs and LightGraphs, and I can tell you for a fact that `add_edge!` is working as intended when you just import LightGraphs. If you're running this inside an atom shell, you might have to restart the Julia kernel after you comment out `using Graphs` to see the fix.

**Comment by sbromberger** [comment] 2017-06-19 14:07
@chathanee I'd really like to be able to help you with this, but unless you post some code that shows the error, I won't be able to do much more than I've already done.

**Comment by juliohm** [comment] 2017-06-19 14:20
@Chathanee we suspect this error is caused by something else in your package, there is no clear indication that this is a bug in LG, it is most likely something overwritten in your code.

If you cannot reduce and isolate the issue to a minimum example, we cannot help you getting the problem solved.

**Comment by jpfairbanks** [comment] 2017-06-19 14:58
If you want to use two packages with the same method you can explicitly indicate which package's method you want. For example LightGraphs.add_edge!

**Comment by sbromberger** [comment] 2017-06-20 01:33
@Chathanee I'm closing this out because I *really* don't think this is a bug in LightGraphs. If you feel otherwise, please feel free to comment further (preferably with code demonstrating the problem) and I'm happy to reopen.

**Closed by sbromberger** 2017-06-20 01:33 UTC
Labels: not a bug

**Comment by sbromberger** [comment] 2017-06-20 05:31
We'll need a lot more detail than what you've provided in order to help. The code (as a gist) would be a good start. Also, the contents of `flow_graph`, `i`, and `sink` will be necessary.

**Comment by Chathanee** [comment] 2017-06-20 05:34
```
flow_graph = DiGraph(length(S)) # Create a flow-graph
flow_edges = Set() #define flow edges
flow_edges_1 = [(i,j,1) for i in S for j in S if i != j]
flow_edges_2 = [(i,j,0) for i in S for j in setdiff(N,S) if i != j]
flow_edges_3 = [(j,i,0) for i in S for j in setdiff(N,S) if i != j]
flow_edges_4 = [(i,j,0) for i in setdiff(N,S) for j in setdiff(N,S)]
flow_edges = union(flow_edges_1,flow_edges_2,flow_edges_3,flow_edges_4)
print(flow_edges)

#capacity_matrix = Matrix()
capacity_matrix = zeros(Int, length(N), length(N))  # Create a capacity matrix

for u in N 
  for v in N
    for k in flow_edges
      u, v, F = k 
      add_edge!(flow_graph, u, v)
      capacity_matrix[u,v] = F
    end
  end
end

max_flow_1 = Set()

for i in S        
  source = Set()
  push!(source, i)
  print(source)
  for j in source
    global tempvert = Set()
    tempvert = setdiff(S, j)
    print(tempvert)
  while true
    if !isempty(tempvert)
      sink = Set()
      sink = pop!(tempvert)
      print(sink)
    else
      break;
    end

F, flow_value = maximum_flow(flow_graph, i, sink)
```
Here S and N are just sets.

**Comment by sbromberger** [comment] 2017-06-20 05:36
This doesn't help. Please note: I am asking for very specific information.

1) Please paste the *actual* code as a gist (gist.github.com) so that the line numbers in the gist correspond to the line numbers in the error message.

2) Please provide the parameters for each of the arguments `flow_graph`, `i`, and `sink` as they are called in the last line of the code above. What does `flow_graph` look like? How many nodes/edges? Can you paste the contents of a `savegraph(STDOUT, flow_graph)` in a gist?

The code above does not allow me to reproduce your error, so I cannot help given what you've provided.

**Comment by Chathanee** [comment] 2017-06-20 05:41
@sbromberger okay..

**Comment by Chathanee** [comment] 2017-06-20 05:46
@sbromberger Okay I added the code as gist.

**Comment by juliohm** [comment] 2017-06-20 05:49
@Chathanee can you please make sure you run the code you are uploading somewhere before you upload it? Does it reproduce the issue you are having locally? This is the **only** way we can help.

A checklist for you:

- [ ] Reduce the code to a minimum
- [ ] Run it locally and make sure the issue is there
- [ ] Upload the gist and *share* the link on this conversation

**Comment by Chathanee** [comment] 2017-06-20 05:54
@juliohm Yes, It produces the same error as follows;

`LoadError: BoundsError: attempt to access 5-element Array{Int64,1} at index [9]
while loading /Users/xxx/ip.jl, in expression starting on line 56
 in push_relabel(::LightGraphs.DiGraph, ::Int64, ::Int64, ::LightGraphs.DefaultCapacity) at push_relabel.jl:32
 in #maximum_flow#133(::LightGraphs.PushRelabelAlgorithm, ::Int64, ::Function, ::LightGraphs.DiGraph, ::Int64, ::Int64, ::LightGraphs.DefaultCapacity) at maximum_flow.jl:184
 in maximum_flow(::LightGraphs.DiGraph, ::Int64, ::Int64) at maximum_flow.jl:181
 in macro expansion; at ip.jl:110 [inlined]
 in anonymous at <missing>:?
 in include_string(::String, ::String) at loading.jl:441
 in include_string(::String, ::String) at sys.dylib:?
 in include_string(::Module, ::String, ::String) at Compat.jl:1492
 in (::Atom.##59#62{String,String})() at eval.jl:73
 in withpath(::Atom.##59#62{String,String}, ::String) at utils.jl:30
 in withpath(::Function, ::String) at eval.jl:38
 in macro expansion at eval.jl:71 [inlined]
 in (::Atom.##58#61{Dict{String,Any}})() at task.jl:60
`

The link for the gist is
[(https://gist.github.com/Chathanee/95c564244ea0dbad6f0f0c820235a58a)]

**Comment by juliohm** [comment] 2017-06-20 05:58
This is not a minimum working example, it has a bunch of other things that don't relate to LG. I don't have Gurobi installed here on my laptop for instance, can't help.

**Comment by sbromberger** [comment] 2017-06-20 05:59
@Chathanee -

1) The gist you posted does not have line numbers that match up with your error message. For example, like 56 should be something that results in a `getindex` but line 56 in the gist is a `while true`.

2) I still have *no idea* what `flow_graph`, `i`, and `sink` are when the code fails. What are their values?

If I had to guess just based on the error message, you are trying to access vertex 9 of a 5-node graph. This is, of course, not possible.

**Comment by Chathanee** [comment] 2017-06-20 06:01
that's okay.

**Comment by sbromberger** [comment] 2017-06-20 06:09
@Chathanee if you can't / won't provide enough information for us to help debug, we simply can't help. There's not enough information her for us to do any more than we've done.

This is the second bug report I've been involved in where there has not been sufficient information to proceed. I would suggest you take a look at http://contribution-guide-org.readthedocs.io/#what-to-put-in-your-bug-report for some guidelines on writing more effective reports. This way we can help you more effectively.
