### ISSUE TITLE
Running DiGraph on JuliaBox

### ISSUE THREAD

**Issue by tenthdimension** [JuliaGraphs/LightGraphs.jl#283] opened 2016-02-01 14:03 UTC
Good morning Seth, 

Is this code right? 

file = open("edges", "r")
g = DiGraph(100) #create 100-vertex graph

for 1 in readlines(file)

(u,v) = split(chomp(l),'') 
intu = parse(Int,u)
intv = parse(Int,v)

add_edge!(g,intu+1,intv+1)

end

close(file)

I opened a Notebook on juliabox.org, Julia 0.5.0-dev, clicked Cell > Run All, and got 

LoadError: UndefVarError: DiGraph not defined
while loading In[12], in expression starting on line 2

 [inlined code] from ./essentials.jl:80

In researching, I also found the method is_directed(g) exists. Can I put that right after opening file? 

Thank you! Kevin

**Comment by tenthdimension** [comment] 2016-02-01 14:22
Seth, since I have close to zero experience programming, I'm discovering incorrect code here.

**Comment by tenthdimension** [comment] 2016-02-01 14:24
I have this now, seems less incorrect 

file = open("edges", "r")

lines = readlines(file)
counter = 1

g = function DiGraph(100) #create 100-vertex graph

for 1 in readlines(file)

(u,v) = split(chomp(l),'') 
intu = parse(Int,u)
intv = parse(Int,v)

add_edge!(g,intu+1,intv+1)

end

close(file)

**Comment by jpfairbanks** [comment] 2016-02-01 14:27
I think you forgot `using LightGraphs` at the top of the notebook, you will also likely need to install LightGraphs using `Pkg.add("LightGraphs")`

**Comment by tenthdimension** [comment] 2016-02-01 14:37
Hi JP, doesn't Notebook on juliabox.org, Julia 0.5.0-dev already contain the latest packages? 

I added using LightGraphs, thank you, looks like this now

using LightGraphs
file = open("edges", "r")
lines = readlines(file)
counter = 1
g = function DiGraph(100) #create 100-vertex graph

for 1 in readlines(file)
(u,v) = split(chomp(l),'') 
intu = parse(Int,u)
intv = parse(Int,v)
add_edge!(g,intu+1,intv+1)
end

close(file)

**Comment by tenthdimension** [comment] 2016-02-01 14:39
got warning

LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading In[26], in expression starting on line 1

 in require at ./loading.jl:357
 in stale_cachefile at ./loading.jl:553
 in recompile_stale at ./loading.jl:570
 in _require_from_serialized at ./loading.jl:164
 in _require_from_serialized at ./loading.jl:193
 in require at ./loading.jl:323
 [inlined code] from ./essentials.jl:80

**Comment by sbromberger** [comment] 2016-02-01 15:34
As @jpfairbanks mentioned, even if the package is installed, you need to import the code into your session via `using`.

Ignore the warnings. They're probably juliabox-specific.

Here's the code that should work:

```
using LightGraphs
g = DiGraph(100) #create 100-vertex graph
file = open("edges", "r")
for l in readlines(file)
    (u,v) = split(chomp(l),' ') 
    intu = parse(Int,u)
    intv = parse(Int,v)
    add_edge!(g,intu+1,intv+1)
end
close(file)
```

**Comment by jpfairbanks** [comment] 2016-02-01 15:39
I tried it with v0.4 (the stable version that most packages test against) and LightGraphs was not installed.
Pkg.add("LightGraphs") fixed it. `using LightGraphs` fails but so does `using Iterators`

**Comment by jpfairbanks** [comment] 2016-02-01 15:44
Ehh restarted the notebook and then it worked.

**Comment by tenthdimension** [comment] 2016-02-01 15:55
Hi guys. This is what I got, Julia 0.4.3 on a Notebook on JuliaBox:

Pkg.add("LightGraphs")
using LightGraphs
g = DiGraph(100) #create 100-vertex graph
file = open("edges", "r")
for l in readlines(file)
    (u,v) = split(chomp(l),' ') 
    intu = parse(Int,u)
    intv = parse(Int,v)
    add_edge!(g,intu+1,intv+1)
end
close(file)

Then in a red box
INFO: Initializing package repository /home/juser/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Installing ArrayViews v0.6.4
INFO: Installing AutoHashEquals v0.0.9
INFO: Installing Clustering v0.5.0
INFO: Installing Combinatorics v0.2.0
INFO: Installing Compat v0.7.8
INFO: Installing Distances v0.3.0
INFO: Installing Docile v0.5.23
INFO: Installing GZip v0.2.18
INFO: Installing Iterators v0.1.9
INFO: Installing LightGraphs v0.5.0
INFO: Installing LightXML v0.2.1
INFO: Installing MacroTools v0.2.1
INFO: Installing ParserCombinator v1.7.4
INFO: Installing Polynomials v0.0.5
INFO: Installing Requires v0.2.2
INFO: Installing StatsBase v0.7.4
INFO: Installing StatsFuns v0.2.0
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Building LightXML
INFO: Package database updated
INFO: Precompiling module LightGraphs...
INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Iterators.ji for module Iterators.
WARNING: Module Compat uuid did not match cache file
WARNING: deserialization checks failed while attempting to load cache from /home/juser/.julia/lib/v0.4/Iterators.ji
INFO: Precompiling module Iterators...
INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/Iterators.ji for module Iterators.
WARNING: Module Compat uuid did not match cache file

and
LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading In[2], in expression starting on line 2

 in require at ./loading.jl:252
 in stale_cachefile at loading.jl:441
 in recompile_stale at loading.jl:458
 in _require_from_serialized at loading.jl:83
 in require at ./loading.jl:251

**Comment by tenthdimension** [comment] 2016-02-01 16:03
I just Run All again, 0.4.3 again, and got this

Pkg.add("LightGraphs")
using LightGraphs
g = DiGraph(100) #create 100-vertex graph
file = open("edges", "r")
for l in readlines(file)
    (u,v) = split(chomp(l),' ') 
    intu = parse(Int,u)
    intv = parse(Int,v)
    add_edge!(g,intu+1,intv+1)
end
close(file)

In red:
INFO: Nothing to be done

**Comment by sbromberger** [comment] 2016-02-01 16:09
Yeah, the issue is that Juliabox is choking on Compat.jl and precompilation, which in turn is causing Iterators to fail, which is causing a precompile failure up the chain. This isn't something that LG can fix, unfortunately, unless we start getting rid of dependencies (see #278).

@tenthdimension - if you run this code inside a Julia REPL (on your own machine, for example), it should work.

**Comment by tenthdimension** [comment] 2016-02-01 16:21
Oh boy. I installed REPL on my MBP last November but had to trash the hard-drive and cable. Will re-install again. Thanks Seth!

**Comment by tenthdimension** [comment] 2016-02-01 16:28
Seth, before determining how many vertices a graph has, what method do you use to check? For instance, that a graph has 100 vertices.

**Comment by sbromberger** [comment] 2016-02-01 16:32
> Seth, before determining how many vertices a graph has, what method do you use to check? For instance, that a graph has 100 vertices.

I extracted all the integers from your the file and created `eset = Set{Int}()` which contained all those integers. I then did `(mn, mx) = extrema(eset)` and made sure that the set equaled `Set{Int}(mn:mx)`.
`mn,mx` turned out to be `0, 99`, and the set was contiguous, so I knew that there were 100 vertices.

**Comment by tenthdimension** [comment] 2016-02-01 16:38
Thank you Professor Seth. Are you selling any books?

**Comment by sbromberger** [comment] 2016-02-01 16:41
No, but the [best one (for LightGraphs)](http://lightgraphsjl.readthedocs.org) is free!

**Comment by tenthdimension** [comment] 2016-02-01 16:44
Thank you! :-)

**Comment by sbromberger** [comment] 2016-02-01 16:57
OK, @jpfairbanks' steps work. Do this in JuliaBox:

1) start up the 4.3 kernel
2) `Pkg.add("LightGraphs")`
3) `using LightGraphs` - this should fail after a bit.
4) Restart the kernel
5) `using LightGraphs` again - this should work
6) `g = DiGraph(100)` to prove it.

**Comment by tenthdimension** [comment] 2016-02-01 17:11
Seth, how do I check if the code worked?

**Comment by sbromberger** [comment] 2016-02-01 17:26
If you get a DiGraph from step 6 (try typing just `g` to see what's output) then it worked and you can load the edges from the file.

**Comment by tenthdimension** [comment] 2016-02-01 17:35
Cool, g={100, 945} directed graph and closeness_centrality(g) is 

100-element Array{Float64,1}:
 0.438053
 0.480583
 0.464789
 0.454128
 0.485294
 0.480583
 0.4125  
 0.39759 
 0.445946
 0.466981
 0.445946
 0.405738
 0.460465
 ⋮       
 0.5     
 0.482927
 0.454128
 0.430435
 0.473684
 0.469194
 0.404082
 0.460465
 0.402439
 0.441964
 0.464789
 0.473684

**Comment by sbromberger** [comment] 2016-02-01 17:50
That graph looks correct (though I haven't validated the closeness centrality results). Congratulations! I'll close this out - feel free to reply if you need further assistance.

**Closed by sbromberger** 2016-02-01 17:50 UTC

**Comment by tenthdimension** [comment] 2016-02-02 10:37
Good morning Seth, 

Could you help me visualize g using GraphLayout, TikzGraphs, GraphPlot?

I tried this example with Pkg.add("GraphLayout") as the first line, then Run All again without Pkg.add, on JuliaBox 0.4.3, but got the compose.jl, precompile failure you talked about

https://github.com/IainNZ/GraphLayout.jl/blob/master/example/gadfly.jl

**Comment by tenthdimension** [comment] 2016-02-02 12:27
I also have to combine the create vertex, open close file script, with open closeness_centrality and dijkstra functions, all into one script, and am a bit confused over when to fit the AbstractDijkstraState

https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/shortestpaths/dijkstra.jl

into the closeness_centrality 

https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/centrality/closeness.jl

My guess is I should declare the entire dijkstra.jl before closeness.jl? 

1. create vertex, open, close file script
2. declare dijkstra.jl from source
3. declare closeness.jl from source

**Comment by sbromberger** [comment] 2016-02-02 14:57
@tenthdimension did you see the documentation at http://lightgraphsjl.readthedocs.org/en/latest/integration/ ?
