### ISSUE TITLE
ERROR: LoadError: StackOverflowError:

### ISSUE THREAD

**Issue by dpriego87** [JuliaGraphs/LightGraphs.jl#881] opened 2018-05-13 15:53 UTC
I've been trying to save a network with more than 5,600,000 vertices, but it won't succeed after complaining about StackOverflowError . A few months ago, with previous versions of julia and LightGraphs, this wouldn't happen.

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia> Pkg.installed("LightGraphs")
v"0.12.0"

**Comment by sbromberger** [comment] 2018-05-13 15:54
Can you show the code you're using to try to save the graph? Also, is the graph source available somewhere?

**Comment by dpriego87** [comment] 2018-05-13 16:15
It's a state transition graph of a system of around 22 nodes. 
it;s a huge code to calculate the resulting network structure, but this is the line where I save it

`savegraph(joinpath(out_dir,"$(root_name)_att.gml.gz"), attraction_basin, root_name, :gml,compress = true)
`

**Comment by dpriego87** [comment] 2018-05-13 16:45
I just tested with a BA network:

`julia> g = barabasi_albert(5600000,10,is_directed=true)
{5600000, 55999900} directed simple Int64 graph
julia> savegraph("D:/ba.gml.gz",g,"ba",:gml,compress=true)
ERROR: StackOverflowError:

`

if I do it without assigning any name to the graph, another error comes out:

`savegraph("D:/ba.gml.gz",g,:gml,compress=true)
ERROR: MethodError: no method matching savegraph(::String, ::LightGraphs.SimpleGraphs.SimpleDiGraph{Int64}, ::Symbol; compress=true)
Closest candidates are:
  savegraph(::AbstractString, ::LightGraphs.AbstractGraph) at C:\Users\dan_b\.julia\v0.6\LightGraphs\src\persistence/common.jl:87 got unsupported keyword argument "compress"
  savegraph(::AbstractString, ::LightGraphs.AbstractGraph, ::AbstractString) at C:\Users\dan_b\.julia\v0.6\LightGraphs\src\persistence/common.jl:87 got unsupported keyword argument "compress"
  savegraph(::AbstractString, ::LightGraphs.AbstractGraph, ::AbstractString, ::LightGraphs.AbstractGraphFormat; compress) at C:\Users\dan_b\.julia\v0.6\LightGraphs\src\persistence/common.jl:74
  ...
`

**Comment by sbromberger** [comment] 2018-05-13 16:45
A couple of things don't look right here:

1) you're using a really old `savegraph` call. We got rid of symbols to denote file formats well before v0.12.0 - I think it was around 0.10.1.

2) Are you using GraphIO? If not, then GML isn't available in any case. If so, GML is problematic because it relies on ParserCombinator.jl, which is no longer actively maintained.

**Comment by dpriego87** [comment] 2018-05-13 16:49
I used to use the save function, which is not available. The manual for the new function savegraph is not so clear. What is supposed to mean "format=LGFormat" ? What is the type expected there?

**Comment by sbromberger** [comment] 2018-05-13 16:51
`savegraph` uses a type derived from `AbstractGraphFormat` to specify save. But I still want to get back to this issue: what version of LG are you running, and are you using GraphIO?

**Comment by sbromberger** [comment] 2018-05-13 16:55
I can't reproduce the issue:
```
julia> using GraphIO

julia> g = barabasi_albert(5600000,10,is_directed=true)
{5600000, 55999900} directed simple Int64 graph

julia> savegraph("foo.gml", g, GMLFormat())
1
```

**Comment by dpriego87** [comment] 2018-05-13 17:07
I'd never guessed that way of specifying the format. What a cumbersome way of specifying the format anyways. Using symbols was way much handier

I'm using  v"0.12.0"

Yes, I have installed GraphIO

I could finally save my graphs. So, this was more a problem of clarity in the manual than an issue per se.

**Comment by sbromberger** [comment] 2018-05-13 17:10
You found an interesting bug in the way were were dispatching on `savegraph`, though. I think I've fixed it.

**Comment by mbesancon** [comment] 2018-06-04 22:25
@sbromberger what's the status on this, fixed on a PR?

**Closed** 2018-06-05 03:41 UTC
