### ISSUE TITLE
Improving speed of `diffusion`

### ISSUE THREAD

**Issue by nickeubank** [JuliaGraphs/LightGraphs.jl#724] opened 2017-08-22 18:48 UTC
By all standards, `diffusion` is pretty darn fast, but I'm running into problems late in diffusion runs on large networks. I can get through a set of ~1,000 50-step simulations in about 50 minutes on a 10-million node network, but I’m already over 24 hours for a set of 100-step simulations, so it’s really the later stages of the diffusion process causing problems. 

Much of that I’m sure is because there are just exponentially more infected vertices in later steps, but it strikes me the one place that there’s “wasted effort” is in re-calculating whether to spread to already-infected nodes.

The thing I’ve been playing with is trying to remove already-infected vertices from `outn` before the `randsubseq` function (line 57), but subsetting seems more costly than leaving them in:

    not_yet_infected_neighbors = setdiff(outn, infected_vertices)
    union!(new_infections, randsubseq(not_yet_infected_neighbors, local_p))

But it slowed down a lot – that `setdiff` is far more costly then a few more random draws. Similarly if I first convert `outn` to a set, then do `setdiff!` then converted back for use in `randsubseq` (unsurprisingly I guess given the conversions):

    outn = Set(outn)
    setdiff!(outn, infected_vertices)
    union!(new_infections, randsubseq(collect(outn), local_p))

This may just not be fixable, but suggestions welcome!

[Cross-Post (sorry!) with Discourse](https://discourse.julialang.org/t/suggestions-for-performance-enhancement-in-lightgraphs-diffusion/5486)

**Comment by nickeubank** [comment] 2017-08-22 19:53
As per suggestion of @sbromberger, changing `infected_vertices` from `IntSet` to `Set{T}` and subsetting neighbors. Sadly in line with past experiments -- about 10x slower. `setdiff` is just SLOW compared to drawing random numbers. :/

PRE:

      L31:   infected_vertices = IntSet(initial_infections)

      L57:  union!(new_infections, randsubseq(outn, local_p))

POST:

      L31:   infected_vertices = Set{T}(initial_infections)

      L57:   not_yet_infected_neighbors = setdiff(outn, infected_vertices)
                union!(new_infections, randsubseq(not_yet_infected_neighbors, local_p))


Benchmarking off:

    g = erdos_renyi(1_000, 5_000, seed=42)
    @benchmark diffusion_rate(g, 0.6, 1)000, normalize=true, watch=collect(300:700),
    initial_infections=[400])

Pre-change benchmark:

    BenchmarkTools.Trial: 
    memory estimate:  133.56 MiB
    allocs estimate:  1976868
    
    minimum time:     317.943 ms (7.00% GC)
    median time:      334.311 ms (6.20% GC)
    mean time:        344.909 ms (6.02% GC)
    maximum time:     431.233 ms (5.62% GC)
    
    samples:          15
    evals/sample:     1


Post-change benchmark:

    BenchmarkTools.Trial: 
    memory estimate:  47.04 GiB
    allocs estimate:  23627519
    
    minimum time:     85.483 s (5.08% GC)
    median time:      85.483 s (5.08% GC)
    mean time:        85.483 s (5.08% GC)
    maximum time:     85.483 s (5.08% GC)

    samples:          1
    evals/sample:     1

**Comment by nickeubank** [comment] 2017-08-22 20:03
OK, tried avoiding sets in general -- converted new_infections to:

        new_infections = Vector{T}()
        possibly_infected = Int(round(length(infected_vertices) * 2p))
        sizehint!(new_infections, possibly_infected)

and moved to:

         append!(new_infections, randsubseq(outn, local_p))

But almost no change:

    memory estimate:  177.22 MiB
    allocs estimate:  1989092
  
    minimum time:     322.771 ms (6.62% GC)
    median time:      359.394 ms (6.47% GC)
    mean time:        369.338 ms (6.16% GC)
    maximum time:     441.230 ms (5.77% GC)
    
    samples:          14
    evals/sample:     1

**Comment by sbromberger** [comment] 2017-08-22 20:14
Just FYI, since we're likely going to make changes to this function: check out the travis failures on -nightly here: https://travis-ci.org/JuliaGraphs/LightGraphs.jl/jobs/267328067

Maybe we can fix these at the same time.

**Comment by sbromberger** [comment] 2017-08-22 20:15
Also, where possible, use the mutating versions of functions. There is a `setdiff!()`.

**Comment by nickeubank** [comment] 2017-08-22 20:16
I think `setdiff!` only works with sets in both positions, and since `out_neighbors` returns an array, I'd have to convert. Seemed a wash.

**Comment by sbromberger** [comment] 2017-08-22 20:16
Also:

> Sadly in line with past experiments -- about 10x slower. 

Your benchmarks show ~200x slower, no?

**Comment by nickeubank** [comment] 2017-08-22 20:17
Yes, sorry, 200x. Keeping IntSet and using `setdiff(outn, infected_vertices)` was about 10x.

**Comment by nickeubank** [comment] 2017-08-22 20:23
> Just FYI, since we're likely going to make changes to this function: check out the travis failures on -nightly here: https://travis-ci.org/JuliaGraphs/LightGraphs.jl/jobs/267328067

That's no good! Looks like type conversion issues at L37: 
  
            vertices_per_step[1] = T.(watched_initial_infections)

PR in a minute

**Comment by nickeubank** [comment] 2017-08-22 20:29
Seems like I may just be out of luck. There's unnecessary work being done in calculating random draws for already infected vertices, but the cure (pre-filtering neighbors) is worse than the disease. 

May just need to get more hardware.

**Comment by nickeubank** [comment] 2017-08-22 20:31
Squashing is nice: 

    BenchmarkTools.Trial: 
    memory estimate:  95.34 MiB
    allocs estimate:  1973163
    
    minimum time:     276.900 ms (4.62% GC)
    median time:      286.674 ms (5.58% GC)
    mean time:        290.373 ms (5.59% GC)
    maximum time:     313.165 ms (5.59% GC)
    
    samples:          18
    evals/sample:     1

**Comment by nickeubank** [comment] 2017-08-22 20:40
Huh -- tried the mutating `randsubseq` trick and not getting much. At 57:

    randsubseq_buf = zeros(T, outd)
    randsubseq!(randsubseq_buf, outn, local_p)
    union!(new_infections, randsubseq_buf)    

Timing:

    BenchmarkTools.Trial: 
    memory estimate:  168.21 MiB
    allocs estimate:  1007597
    
    minimum time:     316.781 ms (2.78% GC)
    median time:      334.895 ms (3.18% GC)
    mean time:        339.880 ms (3.07% GC)
    maximum time:     372.758 ms (2.50% GC)
    
    samples:          15
    evals/sample:     1

**Comment by sbromberger** [comment] 2017-08-22 21:39
erm. Are you not seeing the benchmark stats I posted in discourse?

**Comment by jpfairbanks** [comment] 2017-08-22 21:50
Is the problem basically a rejection sampler where the rejection rate goes up as the algorithm progresses?

Can you precalculate some additional probabilities to avoid the rejection sampling?

--
Written in extreme haste

**Comment by nickeubank** [comment] 2017-08-22 22:07
@sbromberger That's correct -- my benchmark looks about the same with the `randsubseq!` implementation. Maybe yours was lucky / unlucky draw of diffusion? Or maybe mine is was the outlier. Will re-run over a larger number of simulations. 

@jpfairbanks Not quite I don't think. The expensive loop is "for each infected vertex $v$, iid select whether to spread to each of $v$'s neighbors. If random draw says spread and neighbor not yet infected, infect." As a result:

- as the simulation goes forward, the number of infected vertices on loops over increases exponentially. This is inherent and unavoidable as far as I can tell. 
- Right now the loop runs for every infected vertex even if the neighbors of the vertex are already infected. So it's saying "should I spread along this edge" even if it spread in the past, in which case it effectively ignores the result. That means work is being done that's of no value -- once infected always infected here. But fixing this by filtering the vertex's neighbors down to those who aren't yet infected before drawing random numbers for whether to spread seems to take longer than just drawing a random number for them...

**Comment by sbromberger** [comment] 2017-08-22 22:14
Try
`randsubseq_buf = zeros(T, nv(g))` - it may be that you're not allocating enough memory and that defeats the purpose of the buffer.

**Comment by nickeubank** [comment] 2017-08-22 22:16
benchmarked against 20x of: 

            diffusion_rate(g, 0.6, 1_000, normalize=true, watch=collect(300:700),
            initial_infections=[400])

`randsubseq`
    
    BenchmarkTools.Trial: 
    memory estimate:  2.62 GiB
    allocs estimate:  39716444
    
    minimum time:     7.501 s (5.46% GC)
    median time:      7.501 s (5.46% GC)
    mean time:        7.501 s (5.46% GC)
    maximum time:     7.501 s (5.46% GC)
    
    samples:          1
    evals/sample:     1

`randsubseq!`

    BenchmarkTools.Trial: 
    memory estimate:  3.29 GiB
    allocs estimate:  20182410
    
    minimum time:     8.571 s (3.03% GC)
    median time:      8.571 s (3.03% GC)
    mean time:        8.571 s (3.03% GC)
    maximum time:     8.571 s (3.03% GC)
    
    samples:          1
    evals/sample:     1

> randsubseq_buf = zeros(T, nv(g)) - it may be that you're not allocating enough memory and that defeats the purpose of the buffer.

that's huge though -- the subsequence is drawn from neighbors of vertex we are iterating over -- can't be more then `outd` in size -- that's what you'd get if everyone were drawn.

**Comment by nickeubank** [comment] 2017-08-22 22:21
hmmm... though that gives me an idea. Maybe I can gather all the neighbors of infected vertices, then subsample and merge then in one go. I know julia is anti-vectorization but maybe there are some economies of scale there. Will also have to gather probabilities since vary when `normalize=true`.

**Comment by sbromberger** [comment] 2017-08-22 22:39
No - please check my edited comment. You want the allocation OUTSIDE of the loop - there's no reason to allocate more than once. Put it as L42.

**Comment by nickeubank** [comment] 2017-08-22 22:40
OH! I see. And you re-use the same buffer. I get it now. :) Thanks.

**Comment by sbromberger** [comment] 2017-08-22 22:40
That's right. And you'll want to allocate `nv(g)`, because if you happen to have a wheelgraph and start in the center, you could have `nv(g)-1` neighbors.

**Comment by nickeubank** [comment] 2017-08-22 22:44
Yup, saves 20%. Great call. Will make PR soon. Also what `squash` is getting me on my real graph, so in aggregate, that's 40%!

Benchmark rerunning 20 times:

    BenchmarkTools.Trial: 
    memory estimate:  287.88 MiB
    allocs estimate:  440835
    
    minimum time:     5.195 s (0.40% GC)
    median time:      5.195 s (0.40% GC)
    mean time:        5.195 s (0.40% GC)
    maximum time:     5.195 s (0.40% GC)
    
    samples:          1
    evals/sample:     1

**Comment by sbromberger** [comment] 2017-08-23 00:38
Closed via #732.

**Closed by sbromberger** 2017-08-23 00:38 UTC

**Comment by nickeubank** [comment] 2017-08-23 14:00
@sbromberger  FWIW, [tried a kind of "vectorization" approach where I gather all possible infections](https://github.com/nickeubank/LightGraphs.jl/blob/sample_en_mass/src/traversals/diffusion.jl) then do custom `randsubseq` , and benchmarks are AWFUL. Julia really has killed vectorization.

**Comment by sbromberger** [comment] 2017-08-23 14:13
I think the problem is in 
```
        new_infections = setdiff(neighbors[draws .< probabilities], infected_vertices)
```

In this case you're doing a `setdiff` on a vector, which is going to perform terribly (probably O(n) at the best, maybe O(n^2)).

**Comment by nickeubank** [comment] 2017-08-23 15:28
Tried 

        draws = rand(length(neighbors))
        new_infections = Set(neighbors[draws .< probabilities])
        setdiff!(new_infections, infected_vertices)

Came out better but still much worse than the currently implemented version.

**Comment by sbromberger** [comment] 2017-08-23 15:38
Set creation from a vector is expensive (O(n)) as well. It only makes sense to do it if you're using the set more than once or if there's functionality that performs much better with sets.

Anyway - if you're happy with the performance gains to date, I think we can finish beating this horse :)

**Comment by nickeubank** [comment] 2017-08-23 15:39
:) Yup, should be set. Thanks again!
