### ISSUE TITLE
Dynamic Network Analysis - Subgraphs without 0-degree vertices

### ISSUE THREAD

**Issue by akarpf** [JuliaGraphs/LightGraphs.jl#268] opened 2015-12-29 12:07 UTC
Hi,

First of all, thank you for this great piece of software. Coming from R I was frustrated by the weak performance and I am delighted by the possibilities Julia and LightGraph offer for social network analysis. In this conversion process I am however also encountering a few problems. This is why I am addressing myself to you. 

I am trying to use LG to analyze a graph of which the edges were created at different time points, in a dynamic manner. I therefore wrote the following function:

```Julia 
function netstat(windows,time,elist, numv)
tdf = elist[(time - Dates.Day(windows)) .<= elist[:date] .<= time, [:Source,:Target]];
g   = DiGraph(numv);

for row in eachrow(tdf)
    add_edge!(g, row[:Source],row[:Target])
end
@show (windows, time)
hcat([time for i=1:nv(g)],g.vertices,[windows for i=1:nv(g)],degree_centrality(g),pagerank(g),closeness_centrality(g),local_clustering_coefficient(g),
katz_centrality(g));
end
```
Here **elist** is a DataFrame with the edge list, where each edge contains a timestamp, **numv** is the number of vertices, **windows** is the respective time window which is used and  **time** is the timestamp which serves to iterate through the edge list. 

The problem is now the specification of **numv**. I would like to get the centrality measures of each vertex each at each time point it is observed. There are around 9500 vertices in my edge list and the number of edges is, depending on the window size, between 200 and 3000 per time period. The way `DiGraph()` works (or as I understood it) however forces me to always have a graph with 9500 vertices, although most of them don't even appear at given time period with a given window size (this means there are a lot of 0-degree vertices). I think this slows down my computations tremendously. Of course I could always recode the vertex ids in the edge list, compute the stats, and then recode them again before saving, but this seems a bit cumbersome to me. Is there an easier way to do this?

I found the subgraph functionality but it seems also not to do what I want:
```Julia 
g   = DiGraph(5)
sg = g[[2,4]]
add_edge!(sg,2,4)
```     
The code above yields "ERROR: Vertex 4 not in graph". I actually understood this functionality in this context as to keep only vertices 2 and 4 in the graph. But it seems the vertex numbering is not preserved. It only reduces the number of vertices to two, however with IDs 1 and 2. 

I grateful for every comment!

Best,

Andreas

**Comment by sbromberger** [comment] 2015-12-29 14:56
Thanks for your kind words re LG. You are correct - induced subgraphs (`g[5:8]`) will renumber the vertices. Vertices in LG are always 1-indexed. 

As a very first thought, perhaps you can change your loop a bit: instead of creating the vertices up front and adding the edges at each time period, why not, for each time period, add the vertices for that period (using `add_vertex` / `add_vertices`), add the relevant edges, and then compute the centralities? That way you're computing the information on the graph as it exists at that point in time. If you have the memory you can even save the iterated graphs separately so you can have a sense of how the graph is developing at each time period. 

You might also look at evolvinggraphs.jl, but I don't think they've got all the centrality measures done yet.

**Comment by chameau13** [comment] 2015-12-29 18:50
Thank you very much for your fast reply! Maybe I am misunderstanding something but with `add_vertex!(g)` or `add_vertices!(g, n)` I can only add an additional vertex or a range of vertices respectively, isn't it? What I would like to do however was the following: If at a certain point in time the following edges occur 2 -> 5 and 7 -> 13 would only like to have the vertices [2, 5, 7, 13] in the graph. I suppose this doesn't work, right? Because when I use `add_vertices!(g, 7)` I again have vertices 1:7 in the graph.

**Comment by sbromberger** [comment] 2015-12-29 21:30
yes. Vertices in LG are always one-indexed and consecutive. There's no way to create a "gap".

The way I'd recommend doing this is to figure out how to build the graph iteratively over time so that you're adding vertices in order. You can do this fairly easily by creating a map between the "real" (nonconsecutive) vertex and the one added to the graph. Since you shouldn't be running into memory constraints with 9500 nodes, this should not be an issue.

**Comment by jpfairbanks** [comment] 2015-12-29 23:17
It looks like you are trying to create a table mapping each vertex to a set of centrality scores at each time step. You will have to decide whether you want to treat each time step as a separate graph or accumulate edges over time. Your use of the variable windows indicates to me that you probably want the former approach. 

Degree 0 vertices should have a default value for all measures of centrality. Including them in the graph should not impact your results. If you find otherwise,  file an issue as it is probably a bug.

The simplest way is likely to create the graph from scratch for each window and compute your measures for each vertex and have an additional measure which indicates in this window whether the vertex was included in the graph. Then use that measure when you go for follow on analysis of the measures.

**Comment by chameau13** [comment] 2015-12-29 23:17
Again, thank you very much for your reply. I am not sure how I would be able to build the graph iteratively over time. I am analyzing an empirical network. This means vertex number 99 might appear in two or three consecutive days and then it doesn't show up for a year. 

I think I however found a quite efficient way to circumvent this problem using a dictionary:

```Julia
function netstat(windows, time, elist = el)
tdf  = elist[(time - Dates.Day(windows)) .<= elist[:date] .<= time, [:Source,:Target]];
vid  = sort(unique(vcat(tdf[:Source],tdf[:Target])))
g    = DiGraph(length(vid))
dict = Dict()
for (n,f) in enumerate(vid)
   dict[f] = n
end
for row in eachrow(tdf)
    add_edge!(g,dict[row[:Source]],dict[row[:Target]])
end
@show (windows, time)
hcat(vid,[time for x in 1:length(vid)],[windows for x in 1:length(vid)],degree_centrality(g),pagerank(g),closeness_centrality(g),local_clustering_coefficient(g),katz_centrality(g))
end
```
So now I am creating a graph with the necessary amount of vertices for each time periods and window and then I convert the observed vertex numbers in the corresponding range, as demanded by LG. Since the results are output in order I am simply adding the originally observed range of vertex ids, the timestamp and the respective window size to the results for the purpose of post-analysis. First tests showed: it is much, much faster. Any critique to improve the performance of the function further is warmly welcome!

It would have one more question, which is not related to LG but maybe one of you has an idea: I run the function above in parallel using `pmap`. I would really like to profile the evolution of the network for a whole range of different window sizes (optimally from 1 day to 356 days; the bigger the window size, the bigger the resulting graph obviously), which will consequentially lead to memory problems (at least on my laptop which I have with me during the vacation). Is there a way in Julia to store the result from a loop for example or from pmap to a database on the disk? In R there are packages like `bigmemory` or `ff` for this purpose. I experimented with `SQLite.jl` but this doesn't work at all in parallel in already on one core the database seems to be overwhelmed and locks down. Do you know a solution like this which works for on many cores  and allows me to store my results on disk in order to save memory?

**Comment by jpfairbanks** [comment] 2015-12-30 01:38
Is the additional cost of using all the vertices in each time step coming from LightGraphs or from the other data structures? You can use @time and @profile to get the profiling info.

**Comment by chameau13** [comment] 2015-12-30 12:17
@jpfairbanks This has definitely to do with the additional and unnecessary 0-degree vertices in the graph:
```Julia
a = DiGraph(10000,30);
b = DiGraph(100,30);
@time closeness_centrality(a);
#6.020749 seconds (200.35 M allocations: 7.560 GB, 7.45% gc time)
@time closeness_centrality(b);
#0.002015 seconds (21.67 k allocations: 908.313 KB)
```
I don't see how I could sail round this problem without resorting to the dictionary method used above (my system: OS X El Capitan; 2,7 GHz Intel Core i5; 8 GB 1867 MHz DDR3).

**Comment by jpfairbanks** [comment] 2015-12-31 14:06
That's definitely a bug in either closeness or Dijkstra. The fastest way to alleviate the problem is to add a check degree(v) != 0 in the main loop of closenesscentrality.

 I expect the real problem is that Dijkstra's algorithm doesn't perform such a check before allocating memory. We haven't had anyone use the library this way so it never showed up before. 

In the long run we need to make sure all functions are nearly instantaneous on degree 0 vertices and return sensible default values for the measure they compute.

**Comment by sbromberger** [comment] 2016-01-03 17:23
@jpfairbanks I can fix this easily with closeness centrality, but your suggestion that 
> we need to make sure all functions are nearly instantaneous on degree 0 vertices and return sensible default values for the measure they compute

is a bit harder, since I'm pretty sure some centrality algorithms like pagerank don't have default values for 0-degree vertices.

**Comment by sbromberger** [comment] 2016-01-03 18:04
@chameau13 @jpfairbanks latest master now short-circuits closeness centrality of vertices with degree=0. Give it a try?

**Comment by sbromberger** [comment] 2016-01-05 19:35
@chameau13 @jpfairbanks is there a reason to keep this issue open? (@chameau13 - were you able to implement what you needed?)

**Comment by chameau13** [comment] 2016-01-06 01:49
Hi, if you are interested, I am going to post my solution tomorrow when I am back in the office.

**Comment by sbromberger** [comment] 2016-01-06 17:49
Sure! Thanks.

**Comment by chameau13** [comment] 2016-01-07 00:06
Hi,

I put together a minimal running example. The function is quite extensive though. As mentioned already above, I used a dictionary to overcome the vertex id restrictions in LG and to avoid computing the network metrics also for a lot of zero-degree vertices. Finally I reduce everything into a sqlite database. To run everything in parallel start Julia with `julia -p 4`.

```Julia
#load libraries
import LightGraphs
import DataFrames
using  TimeSeries
using  SQLite
@everywhere using LightGraphs
@everywhere using DataFrames
@everywhere using Iterators

glis  = [DiGraph(50,300) for i in 1:50]
datum = collect(Date(1928,10,24):(Date(1928,10,24)+Dates.Day(49)))
el    = Array(Any,0,3)

for t in 1:length(glis)
for (i,j) in edges(glis[t])
el = vcat(el,hcat(datum[t],i,j))
end
end

el      = DataFrame(el)
windows = [1,3,7];
names!(el,[:date,:Source,:Target])

#function to compute the networkstats
@everywhere function netstat(windows, time, elist = el)
tdf  = elist[(time - Dates.Day(windows)) .<= elist[:date] .<= time, [:Source,:Target]];
vid  = sort(unique(vcat(tdf[:Source],tdf[:Target])))
g    = DiGraph(length(vid))
dict = Dict()
for (n,f) in enumerate(vid)
   dict[f] = n
end
@show (windows, time)
try
hcat(Array(vid),[Dates.format(time, "yyyy-mm-dd") for x in 1:length(vid)],[windows for x in 1:length(vid)],degree_centrality(g),pagerank(g),closeness_centrality(g),local_clustering_coefficient(g),katz_centrality(g))
catch
hcat(0,Dates.format(time, "yyyy-mm-dd"),windows,0,0,0,0,0)
end
end

#helper function to send vars to workers
function sendto(p::Int; args...)
    for (nm, val) in args
        @spawnat(p, eval(Main, Expr(:(=), nm, val)))
    end
end

##
function sendto(ps::Vector{Int}; args...)
    for p in ps
        sendto(p; args...)
    end
end


### set up database ("/path/to/the/database.sqlite")
dbn = SQLite.DB("/Users/name/Desktop/netstats.sqlite")
sch = Data.Schema(["ID","Date","Window","Degree","Pagerank","Closeness","Clustering","Katz"],
                     [Int64, Date, Int64, Float64, Float64, Float64, Float64, Float64],)
sin = SQLite.Sink(sch,dbn,"networkstats")

sendto(workers(), el = el)

###
@time for w in windows
re = @parallel (vcat) for d=datum
netstat(w,d)
end
Data.stream!(Data.Table(re),sin)
sleep(15) #sqlite is a bit lame
re = 0
end
```

I am going to write a function to measure assortativity. I will also post it here, maybe you have some use for it.

**Comment by sbromberger** [comment] 2016-01-07 02:08
Where's your `add_edge!()` call? Right now that graph never gets any edges :)

**Comment by chameau13** [comment] 2016-01-07 02:15
Sorry, I deleted a few lines too much. Now it should run. I updated the comment.

**Comment by sbromberger** [comment] 2016-01-07 03:44
cool. You should see improvements with at least closeness centrality with the latest master. I haven't done any other optimization besides betweenness for 0-deg vertices. I suppose we should look at katz and pagerank.

**Comment by jpfairbanks** [comment] 2016-01-17 17:02
Hi @akarpf, from the script you put in above, it looks like you are treating each time step independently and making a new graph for the edges within the window. In that case it looks like you aren't using the graph as a dynamic data structure. This is certainly the simplest way to do things, as long your model of graphs is that you look only at edges that occur in the window. In this case I think we can close this issue.

If you have specific issues about how this works go ahead an open new issues.

**Comment by akarpf** [comment] 2016-01-17 17:06
Hi! Yeah you can close this one. Regarding the assortativity functions: I hope I can find time the next week to make the necessary changes, if not, in the week after next week I will have time for sure.

**Closed** 2016-01-17 23:11 UTC
