### ISSUE TITLE
[BUG] SimpleGraphs.erdos_renyi with p=1 runs forever

### ISSUE THREAD

**Issue by pjgorski** [JuliaGraphs/LightGraphs.jl#1276] opened 2020-01-16 09:41 UTC
**Description of bug**
Running SimpleGraphs.erdos_renyi with parameter p=1 will make Julia enter a while infinite loop. 
The reason is SimpleGraphs.erdos_renyi uses `function randbn` ([link](https://github.com/JuliaGraphs/LightGraphs.jl/blob/1d4c341fdad3cfb6954361c107c7a5ca32903ae2/src/generators/randgraphs.jl#L41)), which has following code:

    log_q = log(1.0 - p)
    x = 0
    sum = 0.0
    while true
        sum += log(rand(rng)) / (n - x)
        sum < log_q && break
        x += 1
    end

Thus, if `p=1.`, `log_q` will become `-Inf`, so in the loop `sum` will never become smaller than that and the loop will go forever. 

**How to reproduce**

> import LightGraphs
   g=LightGraphs.SimpleGraphs.erdos_renyi(10, 1.)

**Expected behavior**
We should get very quickly a complete graph with given number of nodes. 

**Actual behavior**
The infinite loop is entered. 

**Version information**
 - output from `versioninfo()` surrounded by backticks (``)
`Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD FX(tm)-8350 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, bdver1)`
 - output from `] status LightGraphs` surrounded by backticks (``)
`ERROR: Wrong number of arguments`

**Comment by sbromberger** [comment] 2020-01-20 18:24
I can't repeat this:

```
julia> erdos_renyi(10, 1.0) == complete_graph(10)
true
```

We have [an explicit check](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/SimpleGraphs/generators/randgraphs.jl#L124) for this.

**Comment by pjgorski** [comment] 2020-01-21 11:43
I have version 1.2.0

> julia> pkgs = Pkg.installed();
julia> pkgs["LightGraphs"]
v"1.2.0"

But I don't have function `complete_graph`...

> julia> LightGraphs.SimpleGraph.complete_graph(5)
ERROR: type UnionAll has no field complete_graph

**Comment by simonschoelly** [comment] 2020-01-21 12:40
I think you have to write `LightGraphs.SimpleGraphs.complete_graph(5)`.

The reason is, that there is a type called `SimpleGraph` and a submodule called `SimpleGraphs`. That might sound a bit confusing, but its a convention often used in Julia projects, that the data type is a singular noun and the module that contains it is just the plural version of that noun,

**Comment by simonschoelly** [comment] 2020-01-21 12:42
Also, as you are still using version v1.2.0 of LightGraphs, you have to write `CompleteGraph` instead of `complete_graph`.

**Comment by pjgorski** [comment] 2020-01-21 12:48
I wrote it once with 's', one without and I copied the wrong line. I do have `CompleteGraph`. So I understand, I should upgrade the `LightGraphs`.

**Comment by sbromberger** [comment] 2020-01-22 16:56
Please ensure you're running the latest release. Closing out as a duplicate of #1070

**Closed by sbromberger** 2020-01-22 16:56 UTC
Labels: bug
