### ISSUE TITLE
edge_dists as a matrix (and misc)

### ISSUE THREAD

**Issue by rlouf** [JuliaGraphs/LightGraphs.jl#51] opened 2015-05-20 16:26 UTC
I discovered Julia recently, and was originally put-off by the complicated approach of Graphs.jl. As someone who uses graphs everyday, I can say that the simplicity of the library is a major adoption criterion---look at the success of NetworkX! 

I had a couple of questions regarding the use of edges_dists

1.  Why keeping weights out of the graph structure? Does it lead to major performance improvements? 
2.  Any particular reasons to have it as a matrix? In particular, if the network is huge but sparse, you will be storing a lot of 0s.

Also, just as an aside, I think Julia will be adopted for graphs analysis if we can get the best of all worlds, that is

* A library as simple to use and patch as [NetworkX](https://networkx.github.io/documentation/latest/index.html)
* A library as fast as [graph-tool](https://graph-tool.skewed.de/performance)
* Easy-parallelism for resource-heavy computations (Betweenness centrality for instance)

I'd like to get involved in some way, what are the current priorities?

**Comment by sbromberger** [comment] 2015-05-20 17:00
Hi Rémi,

> Why keeping weights out of the graph structure? Does it lead to major performance improvements?

Yes, it does. In addition to the fact that weights can be typed as different data structures (some people want colors, some want ints, some want floats), the concept of edges having weight is not an intrinsic graph property - many graph operations have no need for weighted edges. (An example is in my own research involving electric smart grids, but I won't bore you with details.) A fundamental design decision for `LightGraphs` is that anything that's not required for basic graph functionality is kept out of the graph structure. This includes edge weights.

That said, I did experiment with them in the early days, and frankly, there's no optimal way of structuring them: sometimes it's more efficient to use a sparse data structure, and other times that gets in the way. I didn't want to do anything complicated, since `LightGraphs` was created specifically because of the frustration I encountered trying to do things with `Graphs`.

Finally, it seemed to me that folks who needed edge weights probably needed other "metadata" as well, and that is best stored in an external datastore (think redis or some other fast datastore). There's no reason you can't create your own representation that uses this external datastore and use LightGraphs as the underlying graph structure; in fact, that's what I'm doing (but not with edge weights, with other geolocation attributes).

> Any particular reasons to have it as a matrix? In particular, if the network is huge but sparse, you will be storing a lot of 0s.

It's not required to be a dense matrix. You can easily pass in a sparse structure if you want - the choice is yours and is dependent on your particular needs. That's the advantage of not having it built in to the graph data structure itself. If you don't care about performance, then a sparse structure is perfectly acceptable as a matrix of edge weights.

> A library as simple to use and patch as NetworkX

That's the goal with `LightGraphs`. I think we're there (or very close).

> A library as fast as graph-tool

That's a primary goal for `LightGraphs` as well, and where we have a tradeoff between functionality and speed, we've prioritized the latter.

> Easy-parallelism for resource-heavy computations (Betweenness centrality for instance)

This is the gold-medal goal. I think we can do some amazing things with parallelism. We're not quite there yet.

> I'd like to get involved in some way, what are the current priorities?

Thanks - we could definitely use help. The current priorities from my perspective are as follows:
1) implement graph algorithms from NetworkX that do not yet exist in `LightGraphs`. Which ones, you ask? Any one that you'd like to see. :)

2) figure out where and how to take advantage of parallelism. Check the `LightGraphs` issues page for the placeholder there.

3) anything you'd like to submit as a PR would be greatly appreciated.

Welcome to Julia!

**Comment by rlouf** [comment] 2015-05-20 17:37
Hi Seth, 

> Finally, it seemed to me that folks who needed edge weights probably needed other "metadata" as well, and that is best stored in an external datastore [...] in fact, that's what I'm doing (but not with edge weights, with other geolocation attributes).

Indeed, I am a *spatial networks* person too (!), and use a lot of metadata along with the graph structure. I have always hesitated between NetworkX's approach of putting everything in the same bag, or keeping everything separate. I agree with you, the latter seems more reasonable, and avoids unnecessary complications at the graph-library level.

Having said that, why asking for a matrix, and not a dictionary 

```
{ edge_id -> weight }
```

? I might be saying something stupid due to my lack of Julia knowledge, but wouldn't it make more sense memory-wise? (and ease of use) Would that entail a performance penalty?

If you agree--and haven't tried this before--I might try to change this in the library. And include the use of weights in the computation of centralities.

My mid-term goal is to build a library to analyse spatial networks based on whatever graph library is the simplest and the fastest. LightGraphs seems to be the best bet :)

**Comment by sbromberger** [comment] 2015-05-20 17:54
Dictionaries are great for storing arbitrary values, but they sort of stink for performance. As an example, see https://groups.google.com/forum/#!topic/julia-dev/_2bF02Kp1fQ for details. Any time you have to iterate over a dict (which you'd have to do to get out_neighbor weights, for example), you're hosed. It's much faster to use a matrix with `[src, dst]` indexing, as that's O(1) lookup and O(n) traversal.

Also, consider the dict data structure: the key would be the edge itself. Then, any algorithm (e.g., dijkstra, bellman) would need to assume that the value is something it could work with. It's better to just explicitly require `edge_dists::AbstractArray{Float64, 2}` if you're going to use edge_dists for anything.

Feel free to try it. Because we don't have benchmarking built in yet (see #45), I would recommend timing the shortest-path algorithms as well as the memory consumption of a very large graph to see what happens. If you manage to get good performance, the next step would be to debate the merits of having edge_dists as a graph attribute. I've had this discussion before, and I've debated with myself since the beginning (see #1), but have always reverted to "it's not a graph elemental, therefore it's external".

LightGraphs is definitely one of the simplest/fastest Julia graph packages out there, and it's more performant than NetworkX by 3+ orders of magnitude on certain things, and almost always faster on the rest.

One thing that would be useful, I think: if you decide to use weights for centrality measures and also decide that you're going to keep edge weights out of the graph structure, then filing PRs for the modified centrality code would be great and something I'd love to merge.

**Comment by rlouf** [comment] 2015-05-20 18:21
> One thing that would be useful, I think: if you decide to use weights for centrality measures and also decide that you're going to keep edge weights out of the graph structure, then filing PRs for the modified centrality code would be great and something I'd love to merge.

I do agree with you on keeping weights out of the graph, so I won't try to get them in :) I might try to include weights in the computation of centralities, though.

I will also try to replace the matrix by a dictionary and look for performance changes. I'd personally prefer dictionaries because it seems more natural to me: weight is associated to an edge. Data usually give you something like edge id and values, and the less steps between data and results, the better!
Rehashing should not be a problem if the weights are kept outside of the graph. The dictionary would only be read by the library. I'll fill a PR with performance comparison when I get around doing that.

> LightGraphs is definitely one of the simplest/fastest Julia graph packages out there, and it's more performant than NetworkX by 3+ orders of magnitude on certain things, and almost always faster on the rest.

As an aside (maybe to add to the "benchmark" issue), showing a clear performance comparison with NetworkX and graph-tool on the website would be a good way to attract users... and to convince developers they are doing the right thing.

**Comment by sbromberger** [comment] 2015-05-20 18:30
> I will also try to replace the matrix by a dictionary and look for performance changes. I'd personally prefer dictionaries because it seems more natural to me: weight is associated to an edge.

You're coming from python, aren't you? :) Julia's mindset may be a bit different, since it's geared for performance: what python calls "premature optimization" and discourages, is actually encouraged more in Julia from what I've seen. Therefore: use dicts when they make sense; use other data structures otherwise. I'd love to see the benchmarks, though: if dicts don't add too much overhead, then it does make sense, perhaps, to use them instead of arrays of Float.

> showing a clear performance comparison with NetworkX and graph-tool on the website would be a good way to attract users... and to convince developers they are doing the right thing.

I used to have that but it was suggested to me that performance comparisons might be perceived as combative/insulting, so I removed them.

**Comment by rlouf** [comment] 2015-05-20 19:00
I do come from Fortran, C++, and then Python :) Although the latter is waaaay slower than the other two, I noticed I spent so little time and mental effort coding that I completely switched and never looked back. I started looking at Julia because of the 'best of all worlds' claim!

> I used to have that but it was suggested to me that performance comparisons might be perceived as combative/insulting, so I removed them.

I get that some people would get offended. But from the users' point of view, looking at performance comparisons is equivalent to comparing prices before buying something. 
At the end of the day a physicist (like me) won't care about the details, and will only be interested in comparing performances and ease of use. Graph-tool shamelessly compares its performance with that of igraph and NetworkX, and rightfully so, I would say: all around me switch from NX to graph-tool because of the performance difference.

**Comment by sbromberger** [comment] 2015-05-20 19:02
We can always add some comparative performance statistics in the docs, I guess. :)

**Comment by jpfairbanks** [comment] 2015-05-20 23:13
> I had a couple of questions regarding the use of edges_dists
>
> Why keeping weights out of the graph structure? Does it lead to major
performance improvements?

Keeping information outside of the graph data structure is a good
compromise between performance and flexibility. You can and more types if
info without affecting the core data structure.

> Any particular reasons to have it as a matrix? In particular, if the
network is huge but sparse, you will be storing a lot of 0s.
>

It should be stored as a sparse matrix which compresses the zeros in csc
format.

> Also, just as an aside, I think Julia will be adopted for graphs analysis
if we can get the best of all worlds, that is
>
> A library as simple to use and patch as (NetworkX)[
https://networkx.github.io/documentation/latest/index.html]
> A library as fast as (graph-tool)[https://graph-tool.skewed.de/performance
]
> Easy-parallelism for resource-heavy computations (Betweenness centrality
for instance)
>

Yes that would be nice.

**Comment by sbromberger** [comment] 2015-05-21 03:22
It's not an apples-to-apples comparison, since I'm not using a 2620M i7 (I'm using a 3.1 GHz i7 in the 2015 13" macbook pro), but I ran pagerank on the same graph they have, and it completed as follows:

```
julia> @time z=pagerank(g);
  69.840 milliseconds (109 k allocations: 43585 KB, 7.41% gc time)
```

From https://graph-tool.skewed.de/performance:
Single-core graph-tool: 0.555 s
igraph: 0.781 s
NetworkX: 34.26 s

So I think it's safe to say that LightGraphs is a contender. Will run betweenness next and update this comment tomorrow.

**Comment by rlouf** [comment] 2015-05-21 08:44
Great news, I am genuinely surprised! (always am with Julia) Wouldn't it be better to start a 'performance comparison' issue with these numbers, for future reference? I am really looking forward for the betweenness comparison! If need be, I am fairly familiar with NetworkX and graph-tool and can run performance comparison tests on my (not so powerful--a 'real world' i5-3320M CPU @ 2.60GHz) computer.

Also, because this issue seems to diverge anyway: what is your workflow like when working on LightGraphs or any Julia library? I am used to working with Python libraries, and am a bit confused here. In particular, I have cloned my forked version (not installed) it, but I cannot run the tests without installing the library... help! I haven't found any particularly helpful resource online, any clue appreciated :)

I have updated the betweenness centrality with weights, added an edge betweenness calculation and extended the code documentation significantly. I'll file a PR once I figured out how to run the tests...

**Comment by rlouf** [comment] 2015-05-21 08:54
With hindsight, I am still surprised by the graph-tool/LightGraphs comparison. Graph-tool's core is C++, so where do they loose speed? Let's worry about it if the betweenness results confirm LightGraphs' speedup...

**Comment by sbromberger** [comment] 2015-05-21 10:59
Alas, betweenness is a different animal entirely:

```
julia> @time z = betweenness_centrality(g);
    6568 seconds      (142 G allocations: 3424 GB, 17.55% gc time)
```
This puts it WELL behind graph-tool (1977.6) and igraph (1182.6), but still way ahead of NetworkX (53716.692). My guess, given the allocation information, is that we could optimize a bit better. Might be worth exploring.

**Comment by sbromberger** [comment] 2015-05-21 11:04
> Also, because this issue seems to diverge anyway: what is your workflow like when working on LightGraphs or any Julia library? I am used to working with Python libraries, and am a bit confused here. In particular, I have cloned my forked version (not installed) it, but I cannot run the tests without installing the library... help! I haven't found any particularly helpful resource online, any clue appreciated :)

What I do is have working code in ~/dev/julia/wip/LightGraphs, and then I symlink ~/.julia/v0.4/LightGraphs to it. I use Atom as an editor, so the project is the former directory. With the symlink, when I test in the REPL, I get the same code I've been working on.

**Comment by sbromberger** [comment] 2015-05-21 11:12
More data:

```
julia> @time z=dijkstra_shortest_paths(g,2);
  20.939 milliseconds (39706 allocations: 10444 KB)
```

This is equivalent to the "single-source shortest paths" test, which has the following results:

graph-tool-singlecore: 6.3ms
igraph: 12ms
NetworkX: 127ms

**Comment by rlouf** [comment] 2015-05-21 11:22
Thanks! So... we loose to graph-tool because of the shortest path algorithm. But something very interesting is that igraph makes up for a 2x slower shortest path algorithm somewhere in the betweenness calculation. I will need to have a look at this!

It may be worth benchmarking elementary graph operations, to have a better idea of where we are losing some time. But maybe later, the results are not bad at all, and it is maybe more important now to expand the algorithms portfolio/document and test the code more extensively?

**Comment by sbromberger** [comment] 2015-05-21 11:30
I think we should be doing both: optimizing where it looks like it might make sense (betweenness centrality) and getting more algorithms in the portfolio. I'd like to see some of the k-core stuff added, but it's a bit beyond my expertise.

**Comment by rlouf** [comment] 2015-05-21 12:07
Agreed!  Maybe it would be best to start an issue per desired algorithm? (and add a 'feature request' tag). There people can provide relevant literature, and start a discussions on whether it should actually be implemented.

Should we also separate general discussions from issues by moving the former to https://gitter.im?

I'll try to fit some dev in my thesis writing schedule over the next few months, starting with betweenness optimisation (I use it a lot).

**Comment by sbromberger** [comment] 2015-05-21 14:03
> Maybe it would be best to start an issue per desired algorithm?

Yes, that sounds great.

> Should we also separate general discussions from issues by moving the former to https://gitter.im?

We're already there thanks to @jpfairbanks - come visit \#JuliaGraphs.

**Comment by rlouf** [comment] 2015-05-21 14:17
> We're already there thanks to @jpfairbanks - come visit #JuliaGraphs.

Great! I can't seem to find it though. Is it public or is it invitation only?

**Comment by sbromberger** [comment] 2015-05-21 14:39
Oops. Try https://gitter.im/JuliaGraphs/LightGraphs.jl.

**Comment by sbromberger** [comment] 2015-05-21 15:34
You inspired me, @rlouf - I went back to profile betweenness centrality and found an optimization in _accumulate_basic that shaves a bunch of time off the calc. I'm currently re-running the benchmarks and will post results here when they're done (couple hours).

**Comment by sbromberger** [comment] 2015-05-31 00:43
OK, I've spent some time on `betweenness_centrality` and `dijkstra` and my new functions result in some nice speedup:

```
julia> @time y = betweenness_centrality2(g);
    1745 seconds      (4677 M allocations: 441 GB, 23.30% gc time)
```

so now we're solidly between `igraph` (1182.6) and `graph-tool` (1977.6).

I'll do some more testing and then commit this in the next week or so.

**Comment by sbromberger** [comment] 2015-05-31 16:01
... and more optimizations:

```
julia> @time y = betweenness_centrality(g);
    1438 seconds      (3768 M allocations: 328 GB, 22.64% gc time)
```

**Comment by sbromberger** [comment] 2015-05-31 17:39
@rlouf @jpfairbanks if you want to try the new faster dijkstra / betweenness, check out the https://github.com/JuliaGraphs/LightGraphs.jl/tree/newdijkstra2 branch. I'd appreciate your feedback.

**Comment by rlouf** [comment] 2015-05-31 17:45
That is very good! I read through the code quickly, what did you do besides using the DefaultDistance() function to initialise distances when not provided, and passing all variable directly (instead of having them in a struct)?

When I was playing around with it, I remember that NetworkX explicitly separated the weighted and unweighted case in the code. The latter can indeed use a BFS rather than Dijkstra, and we might be able to scrape off a bit more time.

I am stuck into writing my thesis today, but I will upload the branch whenever I can and give you some feedback asap!

**Comment by sbromberger** [comment] 2015-05-31 17:48
Lots of things were changed. I totally rewrote Dijkstra, for one - and found a suboptimal case in the original code I took from Graphs (basically, you don't need to initialize the heap with all vertices, and you don't have to update the heap if visited - just re-push. This actually halves the number of comparisons you need to do relative to Graphs.) 

Betweenness still doesn't support weights - but it should be easy to implement now. I'm digging the `DefaultDistance` type. I would never have thought of that on my own.

**Comment by rlouf** [comment] 2015-05-31 17:50
The switch from PriorityQueue to a BinaryHeap was also a good idea. When I played around with dijkstra I found a noticeable improvement!

Yes, the implementation of weights should be relatively straightforward now. What I meant was that NetworkX doesn't use dijkstra in the unweighted case. If you check the code you will see they use a Breadth First Search (equivalent for unweighted graphs).

**Comment by sbromberger** [comment] 2015-05-31 20:59
The original betweenness used a MBH as well - the only PQ we have is in A*, which I think makes sense there (but I haven't optimized it yet). In any case - the branch is ripe for adding weights. Note that I'm not passing weights as a named parameter anymore. The current "correct" way to do it is:

```
function foo{T}(g::AbstractGraph, s::Integer, d::Integer, edge_dists::AbstractArray{T,2} = DefaultDistance()
```

**Comment by sbromberger** [comment] 2015-06-03 14:24
I'm currently confused by https://github.com/JuliaLang/DataStructures.jl/issues/95 - any ideas?

**Comment by sbromberger** [comment] 2015-06-04 23:57
Moving from DataStructures to Base.Collections for binary heaps, I'm seeing tremendous performance improvements:

```
julia> g = readgraph("/Users/seth/Downloads/pgp2.jgz")
{39796, 301498} directed graph

julia> @time z = betweenness_centrality(g);
    1238 seconds      (3769 M allocations: 272 GB, 18.38% gc time)
```

We are now pretty much neck and neck with igraph (1182.6 seconds).

**Comment by sbromberger** [comment] 2015-06-05 04:49
OK. I'm going to close this out since we've gotten off track from the original subject (and that's totally ok). If you'd like to continue the discussion re: performance / benchmarking, please feel free to open another issue and we can post benchmark results there. Thanks to everyone for the help.

**Closed by sbromberger** 2015-06-05 04:49 UTC

**Comment by sbromberger** [comment] 2015-06-17 01:24
Recent test with `map` instead of list comprehension:

```
julia> @time z = betweenness_centrality(g);
    1209 seconds      (3769 M allocations: 272 GB, 18.91% gc time)
```

**Comment by sbromberger** [comment] 2015-06-30 20:37
Performance regression with latest:

```
julia> @time z = betweenness_centrality(g);
    1515 seconds      (3769 M allocations: 272 GB, 16.63% gc time)
```

**Comment by sbromberger** [comment] 2015-08-28 18:23
Latest:

```
Version 0.4.0-pre+7069 (2015-08-28 17:33 UTC) Commit 673d7cc* (0 days old master) x86_64-apple-darwin14.5.0

julia> @time z = betweenness_centrality(g);
1497.858403 seconds (3.77 G allocations: 272.154 GB, 17.79% gc time)
```

**Comment by sbromberger** [comment] 2015-09-11 16:53
Following up since I've got parallelism working:

```
julia> g = readgraph("test/testdata/pgp2.jgz")["pgp"]
{39796, 301498} directed graph

julia> @time z = LightGraphs.parallel_betweenness_centrality(g);
550.892412 seconds (3.88 M allocations: 142.070 MB, 0.01% gc time)
```

This uses 3 cores and beats graph-tool's 4-core performance.
