### ISSUE TITLE
using LightGraphs; using Gadfly; throws error

### ISSUE THREAD

**Issue by ivirshup** [JuliaGraphs/LightGraphs.jl#355] opened 2016-05-04 16:42 UTC
On 0.5, I can't run `using LightGraphs` followed by using `Gadfly` it returns a `MethodError` for `module_uuid(::LightGraphs.#Grid)` ([gist](https://gist.github.com/ivirshup/53b1d142934d73c866b8e0b6d6484647)). This error might be caused by Requires, but I haven't been able to replicate it in a cut down example.

**Comment by sbromberger** [comment] 2016-05-04 20:21
Some troubleshooting steps:

1) Have you cleared your precompile cache?
2) Have you tried updating Requires.jl to the latest master?

**Comment by ivirshup** [comment] 2016-05-04 20:46
Yep, I think I’ve tried with most combinations of master and release from Requires, LightGraphs, and Gadfly.

**Comment by sbromberger** [comment] 2016-05-04 20:48
I note that the latest commit to Requires was an hour or so ago.

**Comment by ivirshup** [comment] 2016-05-04 21:05
Ran `Pkg.update()` again to be sure, and the error is still popping up. Can you not reproduce it?

**Comment by sbromberger** [comment] 2016-05-04 21:21
I don't use Julia 0.5. Just to confirm you've done a `Pkg.checkout` on these packages to make sure you're getting master?

**Comment by ivirshup** [comment] 2016-05-04 21:26
Yep.

```julia
julia> Pkg.status("Gadfly")
 - Gadfly                        0.4.2+             master

julia> Pkg.status("Requires")
 - Requires                      0.2.2+             master

julia> Pkg.status("LightGraphs")
 - LightGraphs                   0.5.3+             master
```

**Comment by sbromberger** [comment] 2016-05-04 21:30
mmm. ok. Thanks. I'm afraid I don't have a 0.5 environment to test, but I'll leave this here in case some of the other regulars can check it out.

**Comment by ivirshup** [comment] 2016-05-23 21:37
I just started getting the same error on julia 0.4.5 with `LightGraphs` and `Plots`.

```julia
julia> using LightGraphs

julia> using Plots
ERROR: MethodError: `module_uuid` has no method matching module_uuid(::Function)
 in stale_cachefile at loading.jl:459
 in recompile_stale at loading.jl:474
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at /opt/homebrew-cask/Caskroom/julia/0.4.5/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at loading.jl:235
 [inlined code] from /Users/isaac/.julia/v0.4/Requires/src/require.jl:11
 in require at /Users/isaac/.julia/v0.4/Requires/src/hook.jl:17

julia> Pkg.status("LightGraphs")
 - LightGraphs                   0.5.5

julia> Pkg.status("Plots")
 - Plots                         0.6.2
```

The same error gets thrown if I'm using `LightGraphs` master.

**Comment by sbromberger** [comment] 2016-05-23 21:52
I can't reproduce:

```
julia> using LightGraphs

julia> using Plots

julia>
```
this is
```
Julia Version 0.4.6-pre+18
Commit 198644a (2016-04-01 03:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.4.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by ivirshup** [comment] 2016-05-23 23:32
Huh. I was able to recreate on JuliaBox using stable versions of everything (same output as above). I've also been able to get this error on development Julia with development versions of everything(same error, waaay more warnings).

**Comment by sbromberger** [comment] 2016-05-23 23:43
I can't reproduce it on JuliaBox either:


[LightGraphs and Plots.pdf](https://github.com/JuliaGraphs/LightGraphs.jl/files/278480/LightGraphs.and.Plots.pdf)

**Comment by ivirshup** [comment] 2016-05-23 23:46
What version of julia is that?

**Comment by sbromberger** [comment] 2016-05-23 23:50
The PDF was from JuliaBox using the 4.5 kernel.

**Comment by sbromberger** [comment] 2016-05-23 23:51
Oh. do this. Get rid of all your precompiled `.ji` files and try fresh.

**Comment by ivirshup** [comment] 2016-05-24 01:04
Still happening locally, and I think is still happening on JuliaBox. On JuliaBox I keep getting intermediate (different) errors while precompiling various packages, so it's hard to get a clean example but [here's what I got](http://bl.ocks.org/ivirshup/raw/4c59b3065318e625b948505eb8ccf232/).

**Comment by sbromberger** [comment] 2016-05-24 20:53
See these lines?

```
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/GZip.ji for module GZip.
INFO: Recompiling stale cache file /home/juser/.julia/lib/v0.4/FileIO.ji for module FileIO.
```

That suggests to me that the cache directory is not clean.

**Comment by sbromberger** [comment] 2016-07-30 07:41
@ivirshup can you try pulling the latest LG master?

**Comment by sbromberger** [comment] 2016-08-29 19:50
Hi @ivirshup - are you still seeing this problem?

**Comment by sbromberger** [comment] 2016-09-04 23:07
Closing this out as unreproducible. Feel free to reply if you're still having problems.

**Closed by sbromberger** 2016-09-04 23:07 UTC
