### ISSUE TITLE
degree_histogram doesn't include counts of vertices of degree 0

### ISSUE THREAD

**Issue by devmotion** [JuliaGraphs/LightGraphs.jl#352] opened 2016-05-02 19:39 UTC
I'm wondering whether it's a bug or a feature that `degree_histogram` doesn't include the counts of vertices of degree 0.

Simple example:
```julia
julia> g = Graph(3)
{3, 0} undirected graph

julia> add_edge!(g, 1, 2)
edge 1 - 2

julia> degree(g)
3-element Array{Int64,1}:
 1
 1
 0

julia> degree_histogram(g)
2-element Array{Int64,1}:
 2
 0
```

The reason for this behaviour is that in the definition
```julia
degree_histogram(g::SimpleGraph) = (hist(degree(g), 0:nv(g)-1)[2])
```
the lower bound of the bins is 0. This excludes all vertices of degree 0 from the histogram (see also the documentation of [`hist`](http://docs.julialang.org/en/release-0.4/stdlib/math/#Base.hist)).

Is this behaviour intended?

**Comment by CarloLucibello** [comment] 2016-05-02 20:12
I don't know if it is intended but I think it is safer to just remove this function from lightgraphs

**Comment by jpfairbanks** [comment] 2016-05-02 20:34
I think this function is important. Degree distribution impacts the performance of almost every operation on graphs.  You should always know the degree distribution of the graphs with which you are working. 

I think we might want to report the number of 0 degree vertices. Does changing `degree_histogram(g::SimpleGraph) = (hist(degree(g), 0:nv(g)-1)[2])` to `degree_histogram(g::SimpleGraph) = (hist(degree(g), -1:nv(g)-1)[2])` give the right answer for that case?

If we are going to "fix" this, what are the backwards compatibility implications? For the immediate workaround, you can just subtract `degzeros = nv(g) - sum(degree_histogram(g)` right? Of course that will break if we change the default behavior.

**Comment by devmotion** [comment] 2016-05-02 21:23
Yes, `(hist(degree(g), -1:nv(g)-1)[2])` gives the right answer. That's my workaround so far.

**Comment by sbromberger** [comment] 2016-05-02 23:14
It was intended behavior. 0-degree distributions, where needed, can be determined by subtracting the sum of the others, as @jpfairbanks says. The reason we do / I did it this way is because it's a nice easy 1-indexed vector where the index corresponds to the bin.

**Comment by jpfairbanks** [comment] 2016-05-03 02:33
I really like that indexing justification. We should keep that and just
document for new users.

**Comment by sbromberger** [comment] 2016-05-03 15:47
Closing out in anticipation of a doc PR :)

**Closed by sbromberger** 2016-05-03 15:47 UTC

**Comment by CarloLucibello** [comment] 2016-05-04 06:06
issues should  not be closed until the problem is fixed

**Comment by sbromberger** [comment] 2016-05-04 13:18
I'm not aware that there is a problem to be fixed. The question in the original post was "is this intended behavior?" The answer is yes, it is intended behavior. 

A workaround was suggested, and some discussion regarding the history of the design decision ensued. 

I'm happy to continue discussion but I'm not sure there's anything to resolve.

**Comment by jpfairbanks** [comment] 2016-05-04 13:41
#354
